# Basic Introduction to Julia
とりあえずJuliaに触ってみよう.
基本的なスクリプト言語と書き方は同じです.
なんて言ったって, use like python, run like c, ですし.

## see also here
 - https://docs.julialang.org/en/latest/
 - https://gitter.im/JuliaLang/julia  
Generally, discussued Juylia0.6.2

## 1. 開発用ツール
Juliaにはたくさんのdocumentation toolがあるけどたくさんありすぎて紹介しきれないので, そのうちのいくつかを紹介.

Juliaはひとつの関数に対して複数のメソッドを多重ディスパッチすることが可能であるため, 特に関数に関するtoolが多いです.

- methods()
- @which
- fieldnames()
- typeof()
-  @code_lowered
- ?

In [1]:
methods(copy) # methods()...ある名前で定義されているメソッドを出力

# 45 methods for generic function "copy":
copy(e::Expr) at expr.jl:25
copy(s::IntSet) at intset.jl:34
copy(o::ObjectIdDict) at dict.jl:320
copy(src::Base.dSFMT.DSFMT_state) at dSFMT.jl:32
copy(src::MersenneTwister) at random.jl:91
copy(src::Base.LibGit2.StrArrayStruct) at libgit2/strarray.jl:32
copy(A::Base.Pkg.Types.VersionSet) at pkg/types.jl:49
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem) at pkg/resolve/versionweight.jl:101
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuild) at pkg/resolve/versionweight.jl:159
copy(a::Base.Pkg.Resolve.VersionWeights.VersionWeight) at pkg/resolve/versionweight.jl:219
copy(a::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue) at pkg/resolve/fieldvalue.jl:69
copy(r::Range) at range.jl:433
copy(x::Number) at number.jl:32
copy{T<:Array{T,N}}(a::T) at array.jl:70
copy(M::SymTridiagonal) at linalg/tridiag.jl:75
copy(M::Tridiagonal) at linalg/tridiag.jl:393
copy(A::LowerTriangular) at linalg/triangular.jl:33
copy(A::Base.LinAlg.UnitLowerTriangular) at linalg/triangular.jl:33
copy(A::UpperTriangular) at linalg/triangular.jl:33
copy(A::Base.LinAlg.UnitUpperTriangular) at linalg/triangular.jl:33
copy{T,S}(A::Symmetric{T,S}) at linalg/symmetric.jl:96
copy{T,S}(A::Hermitian{T,S}) at linalg/symmetric.jl:97
copy(M::Bidiagonal) at linalg/bidiag.jl:193
copy{T,P<:SparseMatrixCSC{Tv,Ti<:Integer}}(ra::Base.ReshapedArray{T,2,P,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}}) at sparse/sparsematrix.jl:186
copy(S::SparseMatrixCSC) at sparse/sparsematrix.jl:201
copy{Tv<:Float64}(A::Base.SparseArrays.CHOLMOD.Sparse{Tv}, stype::Integer, mode::Integer) at sparse/cholmod.jl:596
copy(A::Base.SparseArrays.CHOLMOD.Sparse) at sparse/cholmod.jl:1130
copy(x::AbstractSparseArray{Tv<:Any,Ti<:Any,1}) at sparse/sparsevector.jl:752
copy(A::Base.SparseArrays.CHOLMOD.Dense) at sparse/cholmod.jl:1129
copy(a::AbstractArray) at abstractarray.jl:607
copy(d::Dict) at dict.jl:373
copy(a::Associative) at dict.jl:123
copy(s::Set) at set.jl:41
copy(b::Base.AbstractIOBuffer) at iobuffer.jl:38
copy(A::Base.LinAlg.LQ) at linalg/lq.jl:48
copy(F::Base.LinAlg.Schur) at linalg/schur.jl:216
copy(F::Base.LinAlg.GeneralizedSchur) at linalg/schur.jl:217
copy(C::Base.LinAlg.Cholesky) at linalg/cholesky.jl:349
copy(C::Base.LinAlg.CholeskyPivoted) at linalg/cholesky.jl:350
copy(J::UniformScaling) at linalg/uniformscaling.jl:22
copy{T}(a::Base.Pkg.Resolve.VersionWeights.HierarchicalValue{T}) at pkg/resolve/versionweight.jl:71
copy(A::Base.SparseArrays.CHOLMOD.Factor) at sparse/cholmod.jl:1131
copy(x::AbstractString) at deprecated.jl:49
copy(x::Tuple) at deprecated.jl:49
copy(md::MbedTLS.MD) at /home/takesei/.julia/v0.5/MbedTLS/src/md.jl:93

In [67]:
@which(copy([1, 2, 3])) # @which...関数のどのメソッドが呼ばれているかを出力

copy{T<:Array{T,N}}(a::T) at array.jl:70

In [68]:
fieldnames(Hermitian) # filednames()...構造体の中身のタイプを出力

2-element Array{Symbol,1}:
 :data
 :uplo

In [4]:
typeof([1;2;3]) # typeof()... 型を出力, c.f. ;は改行, つまりこれは列ベクトル

Array{Int64,1}

In [69]:
@code_lowered sin(sqrt(3)) # @code_lowered...どんな処理が発生してるかを確認できる. sqrt(3)は√3でもok.

LambdaInfo template for sin(x::Float64) at math.jl:202
:(begin 
        nothing
        SSAValue(0) = (Base.cconvert)(Base.Math.Float64,x)
        SSAValue(1) = (Core.ccall)((Core.tuple)("sin",Base.Math.libm),Base.Math.Float64,(Core.svec)(Base.Math.Float64),(Base.unsafe_convert)(Base.Math.Float64,SSAValue(0)),SSAValue(0))
        return (Base.Math.nan_dom_err)(SSAValue(1),x)
    end)

またIntractiveShellにてjuliaを使っている場合だけですが.REPLにて"?"を打ち込むとhelpモードに入ります.

In [6]:
# ?copy...copyのヘルプが出ます

-----

## 2.Array
基本的な構文はmatlabと類似しています.

### 宣言方法と代入方法

In [7]:
a = Vector{Float64}(5) #5つのfloat64値からなる一次元配列の生成
a = [1 2 3 4 5]

cv = [1;2;3;4;5] # 列ベクトル
rv = [1 2 3 4 5] # 行ベクトル

println(cv)
println(rv)

[1,2,3,4,5]
[1 2 3 4 5]


In [8]:
a[3] = 100 # 配列aの"3つめ"の要素を100に変更. 線形indexを使用しています.
a

1×5 Array{Int64,2}:
 1  2  100  4  5

In [9]:
b = Matrix{Float64}(4,2) # size(4, 2)からなるFloat64型行列を生成

c = Array{Float64}(4,5,6,7) # (4,5,6,7)からなるFloat64配列

mat =  [11 12 13 14
        21 22 23 24
        31 32 33 34] # 直接inlineでMatrixの宣言も可能

3×4 Array{Int64,2}:
 11  12  13  14
 21  22  23  24
 31  32  33  34

In [10]:
mat[1,2] = 4 # 変更方法は同じ.
mat

3×4 Array{Int64,2}:
 11   4  13  14
 21  22  23  24
 31  32  33  34

#### memo1
> memo1: REPL環境を使ってる時, 評価された時に値を返される物の後ろに";"を入れると出力を無視できます.  
> memo2: arrayの値はメモリの場所へのポインタです.

In [11]:
#memo1
mat;

In [12]:
#memo2
a = [1;2;3]
b = a
b[1] = 10
println(a, b)

[10,2,3][10,2,3]


In [13]:
#memo2: aも一緒に変更されたくない場合は"copy"を使います.
a = [1;2;3]
b = copy(a)
b[1] = 10
println(a, b)

[1,2,3][10,2,3]


#### memo2
他にもコンストラクタを使わずにも宣言することが可能です. その場合以下のメソッドが有用.  
いずれも, 引数のArrayのsize/shapeを引き継いだ新しいArrayを返します.

- similar()
- zeros()
- ones()

In [14]:
simA = similar(a) # aと同じ構造の未初期化のaryを返す.
zerosA = zeros(a) # aと同じ構造の全て0のaryを返す.
onesA = ones(a) # aと同じ構造の全て1のaryを返す.

println(simA, zerosA, onesA)

[140129359030288,140129295122720,140129372283376][0,0,0][1,1,1]


#### memo3
1) 配列は[a:b]によって切り出すことが可能.
- [a:b]...配列のa番目からb番目までを切り出す

2) また, aryにはどんな種類のtypeも内包できるため配列の中に配列を含めることももちろん可能です.


In [15]:
#1)
a = [1 2 3 4 5 6 7 8 9 10]
a[1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [16]:
# 2)
a = Vector{Vector{Float64}}(3)
a[1] = [1;2;3]
a[2] = [1;2]
a[3] = [3;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0,2.0,3.0]
 [1.0,2.0]    
 [3.0,4.0,5.0]

また, 入れ子構造になったarrayのcopyにはdeepcopy()を使います.

In [17]:
b = deepcopy(a)
b[1] = [1;3;2]
println(a)
println(b)

Array{Float64,1}[[1.0,2.0,3.0],[1.0,2.0],[3.0,4.0,5.0]]
Array{Float64,1}[[1.0,3.0,2.0],[1.0,2.0],[3.0,4.0,5.0]]


#### memo4
高い実行速度を達成するためにはコード量を減らすことが重要です. 
そのため, Juliaには引数に破壊的代入をもたらすmutationメソッドがあり, そのようなメソッドの末尾には!が付いています.

In [18]:
# mutation method ex.
a = [1;6;9]
scale!(a, 2) # scale!(ary, scalar)...aryをscalar倍

3-element Array{Int64,1}:
  2
 12
 18

----

## 3.制御フロー

Juliaの制御フローは他のスクリプト言語と大して変化はなし.
いつも通りのfor loop, while, ifがあるくらい.

他のものはdocumentを参照.

In [19]:
# for loop
for i=1:5 #1:5でrange, =をinに変えても実行可能.
  println(i)
end

1
2
3
4
5


In [20]:
t = 0
while t < 5
  println(t)
  t+=1
end

0
1
2
3
4


In [21]:
symbol = :asdf

if symbol == :asdf
  println("you said asdf")
else
  println("no idea")
end

you said asdf


#### memo
Juliaのforloopで面白いのは, なんと多重for loopを一列で書ける

In [22]:
for i=1:5, j=2:4
  println(i*j)
end

2
3
4
4
6
8
6
9
12
8
12
16
10
15
20


### 練習問題
http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems
上5問.

制御flow理解できてれば実装できるはず.

#### Q1. (N,N)型で, 体格が-2, 体格の左右隣が1, それ以外が0の行列を作れ. ストラング行列っていうとか

In [70]:
N = 5
#mat = Matrix{Float64}(N, N)
mat = zeros(N, N)
for i=1:N, j=1:N
  if i==j
    mat[i,j] = -2
  elseif i==j+1||i==j-1
    mat[i,j] = 1
  end
end

mat

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

##### Q1. 綺麗なコードver. こっちの方が"juliaらしい"

In [24]:
N=5
A = zeros(N,N)
for i=1:N, j=1:N
  abs(i-j)==1 && (A[i,j]=1)
  i==j && (A[i,j]=-2)
end
A

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

#### Q2. 階上, my_factorial(n)で, n!を出力.

In [25]:
function my_factorial(n)
  ans = 1
  for i=1:n
    ans*=i
  end
  ans  
end
my_factorial(15)
#c.f. ただしこれでは大きい値を扱う形になった時にOverFlowが発生する.(ex. 30を入れるとnegativeになる)

1307674368000

##### こういう時は入力と出力の型を同じにすればよい. one(x)を使用する

In [26]:
function my_factorial(n)
  k = one(n) # one(x)...xと同じ型で値1の数値を返す.
  for i=1:n
    k *= i
  end
  k
end
my_factorial(big(30))

265252859812191058636308480000000

#### Q3.二項問題
nを試行回数, pを成功する確率とした時, n回の内成功した回数XをX=Bin(n,p)と表すとする.  
例えば, Bin(10, 0.5)の時, Xは10回コインを投げた時に表が出てくる回数に等しい.  
  
Xを返すbinomial_rv(n,p)をrand()を用いて実装せよ

In [27]:
function binomial_rv(n,p)
  k=0
  for i=1:n
    p<=rand() && (k+=1)
  end
  k
end

#check
[binomial_rv(10, 0.5) for i=1:5]

5-element Array{Int64,1}:
 5
 5
 7
 5
 5

#### Q4. モンテカルロによる円周率の計算
πを乱数を用いて近似せよ.

**Hint: モンテカルロ法**
[-1, 1]×[-1, 1]の四角形に内包される円があった時, *円の面積はπ*($πr^2$より), *四角形の面積は4*.  
そのため, 乱数を用いて[-1,1]×[-1,1]の部分に一様な乱数で点を打った時, *円周の中に打たれる確率はπ/4*($x^2+y^2$≦1より).  
これを用いてπの大体の値を求めよ.

In [4]:
function montecarlo(n)
  c = 0
  for _=1:n
    x, y = 2rand(2)-1
    √(x^2+y^2)<=1 && (c+=1)
  end
  return 4c/n
end

montecarlo(10000000)

3.1414116

#### Q5. 時系列生成問題
AR1時系列は, $x_{t+1} = \alpha x_i + \epsilon_{t+1}$ では定義されたとする.  
この時それぞれ, $x_0$=0, t=0...T, ソケット$\epsilon_{t}$は独立同分布である(N(0,1)はrandn()によって与えられるとする).  
  
T=200の時,

- α=0
- α=0.5
- α=0.9

の場合のそれぞれのパラメータの時間変化をPlot.jlを用いて示せ.  
また, αの値を表す線にはplot関数にlabelオプションをつけ, ラベルせよ.

In [29]:
using Plots

function ar(T, alpha)
  x=zeros(T+1)
  x[1] = 0.0
  for t=1:T
    x[t+1] = alpha * x[t] + randn()
  end
  x
end

ar (generic function with 1 method)

In [30]:
result = [ar(200, i) for i in [0.0,0.5,0.9]]

gr() # jupyer上でグラフを出力するには必要.
plot(result, label=["a=0", "a=0.5", "a=0.9"], lw=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 30 
 
 
 60 
 
 
 90 
 
 
 120 
 
 
 150 
 
 
 180 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
<polyline clip-path="url(#clip8802)" style="stroke:#009af9; stroke-width:3; stroke-opacity:1; fill:none" points="
 39.3701,186.162 42.1339,147.863 44.8976,140.961 47.6614,163.847 50.4252,192.132 53.189,181.585 55.9528,230.727 58.7165,197.277 61.4803,126.319 64.2441,132.542 
 67.0079,188.559 69.7717,185.626 72.5354,207.239 75.2992,149.61 78.063,142.972 80.8268,165.632 83.5906,202.471 86.3543,225.236 89.1181,208.166 91.8819,174.892 
 94.6457,225.404 97.4094,219.1 100.173,217.365 102.937,148.195 105.701,215.72 108.465,109.239 111.228,210.63 113.992,162.197 116.756,189.859 119.52,190.038 
 122.283,177.688 125.047,190.13 127.811,214.545 130.575,237.978 133.339,204.928 136.102,176.678 138.866,223.783 141.63,157.506 144.394,201.637 147.157,203.699 
 149.921,188.129 152.685,148.117 155.449,156.373 158.213,138.289 160.976,154.919 163.74,150.147 166.504,224.019 169.268,192.19 172.031,166.544 174.795,178.651 
 177.559,184.829 180.323,145.128 183.087,171.477 185.85,198.261 188.614,192.705 191.378,188.991 194.142,212.927 196.906,216.369 199.669,183.663 202.433,204.701 
 205.197,184.544 207.961,148.854 210.724,245.585 213.488,197.041 216.252,171.654 219.016,193.851 221.78,212.396 224.543,201.169 227.307,204.244 230.071,222.873 
 232.835,202.366 235.598,170.677 238.362,199.108 241.126,243.071 243.89,242.114 246.654,164.375 249.417,204.508 252.181,207.663 254.945,214.372 257.709,232.289 
 260.472,123.869 263.236,175.953 266,205.569 268.764,226.773 271.528,148.686 274.291,152.592 277.055,225.923 279.819,95.9007 282.583,189.042 285.346,221.239 
 288.11,189.598 290.874,133.304 293.638,172.296 296.402,242.417 299.165,224.941 301.929,244.934 304.693,210.243 307.457,161.482 310.22,165.825 312.984,113.66 
 315.748,209.784 318.512,186.239 321.276,240.649 324.039,182.328 326.803,235.199 329.567,228.422 332.331,159.754 335.094,195.34 337.858,204.627 340.622,149.687 
 343.386,211.893 346.15,141.299 348.913,128.727 351.677,193.226 354.441,121.885 357.205,200.142 359.969,207.927 362.732,203.929 365.496,163 368.26,149.549 
 371.024,166.459 373.787,131.251 376.551,185.16 379.315,195.542 382.079,183.065 384.843,96.4324 387.606,212.57 390.37,171.053 393.134,192.237 395.898,200.073 
 398.661,144.83 401.425,185.253 404.189,176.526 406.953,185.474 409.717,174.812 412.48,195.273 415.244,209.616 418.008,220.94 420.772,211.325 423.535,181.375 
 426.299,235.573 429.063,177.291 431.827,153.702 434.591,183.989 437.354,199.483 440.118,181.167 442.882,153.49 445.646,190.815 448.409,185.641 451.173,188.639 
 453.937,141.226 456.701,230.319 459.465,178.039 462.228,198.516 464.992,230.756 467.756,188.594 470.52,183.32 473.283,171.777 476.047,283.655 478.811,190.508 
 481.575,134.622 484.339,150.243 487.102,174.331 489.866,166.583 492.63,151.353 495.394,173.277 498.157,162.667 500.921,208.504 503.685,178.755 506.449,210.108 
 509.213,146.864 511.976,192.207 514.74,158.901 517.504,185.908 520.268,195.98 523.031,157.539 525.795,250.298 528.559,201.256 531.323,171.776 534.087,189.797 
 536.85,207.481 539.614,176.429 542.378,222.938 545.142,208.329 547.906,165.611 550.669,159.623 553.433,183.193 556.197,213.89 558.961,194.284 561.724,143.609 
 564.488,168.718 567.252,209.84 570.016,167.757 572.78,204.268 575.543,161.039 578.307,155.447 581.071,147.602 583.835,214.321 586.598,123.947 589.362,179.493 
 592.126,167.713 
 "/>
<polyline clip-path="url(#clip8802)" style="stroke:#e26f46; stroke-width:3; stroke-opacity:1; fill:none" points="
 39.3701,186.162 42.1339,185.152 44.8976,165.285 47.6614,159.739 50.4252,201.396 53.189,199.633 55.9528,243.784 58.7165,197.6 61.4803,186.522 64.2441,195.877 
 67.0079,139.778 69.7717,161.359 72.5354,214.066 75.2992,174.122 78.063,171.903 80.8268,193.998 83.5906,255.832 86.3543,228.961 89.1181,196.681 91.8819,177.407 
 94.6457,169

## 関数
Juliaにはinlineとfunctionを使う2種類の方法があります.  
通常, Juliaの関数は関数の中で最後に評価された値を返します.

In [31]:
# inline
f(x,y) = 2x + y

# long form using "function"
function f(x)
  x+2
end

# 関数呼び出し
f(3,2) |> println
f(2) |> println

8
4


### 多重ディスパッチ
ここでポイントになるのはjuliaのコアな機能の一つである多重ディスパッチです. "一つの関数"であるfに２つのメソッドが存在することがわかるでしょうか. (juliaでは実行可能な関数の部分をメソッドと言います.  
ここではf(::Any,::Any)と, f(::Any)の２つのメソッドが定義されており, この場合関数fに与える引数の個数によりどちらが呼ばれるか決定します.  
  
またJuliaでは型に対応する::Typeの記号を用いることで型にも対応した多重ディスパッチを作ることができます.  
複数のメソッドを呼び出せる関数の呼び出し方をした場合, より厳密に定義されたメソッドが優先的に呼びだされます.

In [32]:
f(x::Int, y::Int) = 3x+2y

f(2,3) |> println # 3x+2y
f(2.0, 3) |> println # 2x+y, ::IntにマッチしないFloatのため.

12
7.0


In [33]:
f{T<:Number}(x::T, y::T) = 4x+10y

f(2,3) |> println # 3x+2y...より厳密に定義されている方なので.
f(2.0, 3.0) |> println # 4x+10y

12
38.0


> note: 型指定の変数化は可能な限り多くの型を含もうとするので, 親の型を明示的に宣言する必要がありません.  
> 例えば, xが数字で, yとzが同じ型の時にmatchするメソッドはこう書きます.

In [34]:
f{T<:Number, T2}(x::T,y::T2,z::T2) = 5x+ 5y+ 5z

f (generic function with 5 methods)

多重ディスパッチはJuliaのコアデザインのため, 後ほどより深く確認していきます.  
特にJuliaの関数は引数の型に応じたメソッド呼び出しの部分に特化しています.  
これは, fの呼び出し可能なメソッドがそれぞれバラバラにコンパイルされることを示していて, 最初に呼ばれたタイミングでコンパイルする仕組み担っていることを意味します.

### 確認問題
というのを意識してこの挙動を確認していきましょう.

In [35]:
f(x,y,z,w) = z+y+z+w
@time f(1,1,1,1)
@time f(1,1,1,1)
@time f(1,1,1,1)
@time f(1,1,1,1.0)
@time f(1,1,1,1.0)

  0.002426 seconds (381 allocations: 21.010 KB)
  0.000002 seconds (4 allocations: 160 bytes)
  0.000001 seconds (4 allocations: 160 bytes)
  0.004844 seconds (1.01 k allocations: 52.800 KB)
  0.000006 seconds (5 allocations: 176 bytes)


4.0

めっちゃはやい()

----

### 関数の他の便利機能
ひとつの関数にまとめて説明.

In [36]:
function test_func(x,y;z=0) # ;XXXでオプション引数. zはオプション引数. デフォ値0
  if z==0
    return x+y, x*y # return時点で関数終了. returnで戻り地設定. 複数値を返すことも可能. tupleで返される.
  else
    return x*y*z, x+y+z
  end
end

test_func (generic function with 1 method)

In [37]:
x,y = test_func(1,2)

(3,2)

In [38]:
x,y = test_func(1,2;z=3)

(6,6)

In [39]:
またJuliaの関数は第一級関数なので, 型の一種です.  
そのため, クロージャ等の関数型プログラムライクなことも可能です.  

LoadError: syntax: incomplete: premature end of input

In [40]:
function func_playtime(x) #zはオプション引数.
  y = 2+x
  function test()
    2y # Juliaの関数スコープ上, 一段回上のスコープで宣言されているものは参照することが可能です.
  end
  z = test() * test()
  return z,test
end
z, test = func_playtime(2)

(64,test)

In [41]:
test()

8

test()に対しyを指定したわけではありませんが, yの値をtest()は持っているのが解ると思います.  
これは, 関数スコープのルール上, 内側の関数は関数として宣言されている同じスコープの変数を参照することが可能だからです.  
これは自己参照のリカーシブ的な挙動であり, トップレベルのスコープというものがグローバルスコープということが予想できるかと思います.  

In [42]:
a = 2

2

これはグローバル変数です.　　
後ほど詳しく見ていきましょう.  
  
最後に, 無名関数の宣言で終わりましょう. 

In [43]:
g = (x,y) -> 2x+y

(::#7) (generic function with 1 method)

名前付き関数と違って, gは何度でも上書きすることが可能です.

In [44]:
g = (x) -> 2x

(::#9) (generic function with 1 method)

無名関数は多重ディスパッチに対応していません. が, v0.5からは名前付き関数同様にコンパイルするようになったため, 速度やパフォーマンスに差はありません.  

また, 関数のカリー化は

In [45]:
g = (x,y) -> 2x+y
h(x) = (y) -> g(x, y)
h(1)(2)

4

と書くことが可能です. 無名関数の応用ですね.

## 型宣言
Juliaで呼ぶ型とは, 他の言語で言うオブジェクトに相当します. (オブジェクトとはJuliaにとっては外様のコンセプト, 名前のついたコンポーネントを持つ型の物とするのであればの話ですが  
型の考えというのは, それが何であるかを示しており, 一方で型のインスタンス化というものは独自のものです.  
例えば, 製造者とモデルの譲歩兎を持つcar型を考えてみた時, トヨタRAV4はcar型のインスタンス化です.  
  
Juliaでは, 以下のようにcarの型を定義してインスタンス化することができます.

In [46]:
type Car
  make
  model
end

mycar = Car("Toyota", "Rav4")

Car("Toyota","Rav4")

あ, そういえばいい忘れましたが, Juliaでは文字列型を"..."で表します. まぁ普通の言語なら問題ないですよね??? (MATLABてめぇ聞いてるか???)　c.f.原文通りです  
typeのフィールドには"."シンタックスを使うことでアクセスが可能です.  

In [47]:
mycar.make

"Toyota"

もしJuliaのパフォーマンスを向上させたいのであれば, 一般的にまずやることはtype宣言を厳密にすることです.  
nameとfieldの属性を持つWorkshopParticipant型(型はキャメルケース)を宣言しようとしたら, この場合

In [48]:
type WorkshopParticipant
  name::String
  field::Symbol #シンボル型, 細かい型に関しては後述
end
tony = WorkshopParticipant("Tony", :physics)

WorkshopParticipant("Tony",:physics)

関数と同様に, typeは変数を用いて型を厳密にすることも可能です. 例えば, StaffMemberという名前とフィールドと年をプロパティに持った型は...

In [49]:
type StaffMember{T<:Number}
  name::String
  field::Symbol
  age::T
end

ter = StaffMember("Terry", :football, 17)

StaffMember{Int64}("Terry",:football,17)

変数を用いたtype宣言のルールは関数と同じです.  

> note: 殆どのネイティブで定義されているJuliaの型(float64やInt等)はこの方法で定義されています.  
> これはつまるところ, ユーザが宣言する型には制限がないということです.  
> 実際, プロトタイプのパッケージがBaseの中に動かされる前までは, たくさんのJuliaの機能のほとんどが最初にこの方法で出発しています.
  
最後に, 抽象型の紹介で終わりましょう. 抽象型はインスタンスにすることはできませんが, 型の木構造を作るためによく使われます.  
今までに出てきたNumber型も抽象型の一つです. 抽象型の宣言はAbstractキーワードを用いて作成します.

In [50]:
abstract Person

type Student <: Person
  name::String
  grade::Number
end

木構造の美しい作り方についてはこちらをご覧くださいませ.  
https://docs.julialang.org/en/release-0.5/manual/types/#abstract-types
  
抽象型の抽象型なども同様に作ることが可能です.

In [51]:
abstract AbstractStudent <: Person

supertype/subtypesを用いる事でtypeの構造を詳しく見ることも可能です.

In [52]:
Person |> subtypes |> println
Student |> supertype |> println

Any[AbstractStudent,Student]
Person


他のバージョンの型の一つに"immutable"というものがあります.  
immutableを使用すると, 型のフィールドの変数の型は変更不可能になります.  
しかし, Juliaは自動的にimmutable型はstackに初期化され, 一方で通常の型はheapで初期化されます.  
これは一般に, immutable型のほうがよりCPUの近くに保存でき, メモリアクセスのコストが低いということを示しています.
多くのJuliaのビルトイン型についてはパフォーマンスを意識しているためimmutableを用いtえ定義されています.

In [53]:
immutable Field
  name
  school
end

ds = Field(:DataScience, [:PhysicalScience, :ComputerScience])

Field(:DataScience,Symbol[:PhysicalScience,:ComputerScience])

### 確認問題
immutableの値に対しては非常に面白い現象を見ることができます. ds.nameとds.schoolは当たり前ですが変更できません. 理由がわかりますか?

In [54]:
ds.name  = :ComutationalStatics

LoadError: type Field is immutable

しかし, この処理は認められます.

In [55]:
push!(ds.school, :BiologicalScience)

3-element Array{Symbol,1}:
 :PhysicalScience  
 :ComputerScience  
 :BiologicalScience

> Hint: ポインタ

-----

Juliaでの一つの重要なことは, 全てのものは型であり, コードすらexpression型に当てはまります.(後述)  
そのため, フィールドにアクセスすることができる関数も同じく型です.  
  
すべての物はコンパイルさっるとCになるだけではなく, すべてのCパーツは常にアクセス可能です.  
例えば, 関数のポインタなんてのも

In [56]:
foo(x) = 2x
first(methods(foo)).lambda_template.fptr

Ptr{Void} @0x0000000000000000

## 基本的な型
Juliaにはたくさんの基本的な型が用意されています. 実際, 型による多重ディスパッチシステムとしてのジュリアを見るにそのコアデザインに関数と型のインタラクションがあることに気づくでしょう.　　

### 遅延評価型
MATLABやパイソンがArrayを組むために簡単な関数を用意しているにもかかわらず, Juliaには特別に作られた型を利用して, 実際の"array"を避ける傾向があります.  
ひとつの例は"Range"です. rangeを定義するためには,
> start:stepsize:end

で定義します.　

In [57]:
a = 1:5 
a |> println
b = 1:2:10 
b |> println

1:5
1:2:9


こいつらはarrayと同じように使えます

In [58]:
a[2] |> println
b[3] |> println

2
5


この場合, bの詳しいところを見ていきましょう.  

In [59]:
a |> typeof |> println
b |> typeof |> println

UnitRange{Int64}
StepRange{Int64,Int64}


bはarrayではなく, StepRange型であるようです.  
StepRangeは自身のフィールドを諒してarrayのように振る舞うことができます

In [60]:
fieldnames(StepRange)

3-element Array{Symbol,1}:
 :start
 :step 
 :stop 

> note: collect()を用いることで, どんな時でもStepRange等の型からArrayを取り出すことができます.

In [61]:
c = collect(a)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

遅延評価型が好まれる理由としては, 本当に必要になるまで計算をしないので, 処理を圧迫しないということです.  
@timeを使ってみてみましょう.

In [62]:
@time a = 1:100000
@time a = 1:100
@time b = collect(1:100000);

  0.000004 seconds (5 allocations: 192 bytes)
  0.000002 seconds (5 allocations: 192 bytes)
  0.000356 seconds (8 allocations: 781.547 KB)


ここでrangeが要する時間は非常に短いということがわかるでしょう.  
だいたいの理由としては, メモリのallocationの回数を大幅に落としているからです.  
StepRangeの場合, インスタンスが作成された時点ではたったの３つの数しか保持していません.  
しかし, bは100000この数を所有しており, rangeとaryの大きな違いを示しています.

### Dictionary
他の一般型の一つにDictionaryがあります.  
key-valueを用いてアクセスします.

In [63]:
d = Dict(:test=>2, "silly"=>:suit)
d[:test] |> println
d["silly"] |> println

2
suit


### Tuples
Tupleは変更不可なimmutableな配列です. めちゃくちゃ早いです.  
(x,y,z,....)で表すことが可能で, ひとつ以上の戻り値を持つ関数は自動的にtupleが戻り値になります.

In [64]:
tup = (2.,3) # typeを一致させる必要はありません.
x,y = (3., "hi") # tupleから複数の変数に分けることが可能です.

(3.0,"hi")

## 問題
http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems  
8~10を解く

Q8. 統計問題

In [65]:
#### 与えられるデータ #####
X = rand(1000, 3)
a0 = rand(3)
y = X * a0 + 0.1 * randn(1000)

##### Q9で使うデータ #####
X = rand(100)
y = 2X + 0.1 * randn(100);

randn(N,3)で与えられtあN×3のArrayと, 結果データが入ったN×1のデータがあったとします.

行列Xを生成する

## メタプログラミング
メタプログラミングはJuliaのでかい機能の一つです. キーとなる考えはJuliaのすべての文はExpression型であるというところです.  
JuliaはExpressionから抽象構文木(AST)を作成します. 実は前出てきたsymbolの部分で少し触れています.  
SymbolはASTの一部分で, これはパースなどで使われる構造です.  
一つの面白いSymbolの比較点は, 例によって文字列の比較点O(n)の一部であるO(1)と関数の表記であるマクロ(@を用いた特殊な関数の表記方法)

故にここまで来たらメタプログラミングをプログラムコードとアウトプットを取り入れるプログラミングであると認識できるでしょう.  
一般的な例としては**"time"**マクロです.

In [66]:
macro my_time(ex)
  return quote
    local t0 = time()
    local val = $ex
    local t1 = time()
    println("elapsed time: ", t1-t0, "seconds")
    val
  end
end

@my_time (macro with 1 method)

exを定義しているこの文章は評価する前と評価したあとの時間を取得して, その間の経過時間を出力します.   
(c.f. 実時間のマクロは今まで見てきたものと同様にアロケーションも計算してくれます)  
  
> Note: $exはmacroの中に表記を補完します. メタプログラミングの詳細にたどるためには通常のプログラム方法とは全く違った考え方をしなくてはならず説明に時間がかかるため, 次回のセッションで扱います.  
  
Q. なぜマクロ?  
A. ひとつの理由はあなたが求めるどんな文法も定義できるからです.  
メタプログラミングはカッら自身の表記を操作するため, どのように動くコードに表記がパースされるかを知る限り, どんな文法でもあなたの文法にすることができます.  
後ほどケーススタディについては扱います.  
また, 別の理由としては, パースするタイミングで実行され, 関数がコンパイルするよりも前に一度だけ呼ばれるからです.

### Juliaのパースと実行の順番について
1. パースの後の抽象高分岐(AST) <- Macro
2. loweringの後のASt <- @code_typed
3. 最適化と型推論の後のAST <- Generated Functions(@code_lowered
4. LLVM IR <- Functions(@code_llvm
5. アセンブリ <- @code_native