# Basic Introduction to Julia
とりあえずJuliaに触ってみよう.
基本的なスクリプト言語と書き方は同じです.
なんて言ったって, use like python and run like c, ですし.

## see also here
 - https://docs.julialang.org/en/latest/
 - https://gitter.im/JuliaLang/julia
Generally, discussued Juylia0.6.2

## 1. 開発用ツール
Juliaにはたくさんのdocumentation toolがあるけどたくさんありすぎて紹介しきれないので, そのうちのいくつかを紹介.

Juliaのメソッドも名前と引数のセットで認識するため, 同じ名前のメソッドでも引数に応じた複数の処理を一つの名前のメソッドに定義できます.

- methods()
- @which
- fieldnames()
- typeof()
-  @code_lowered
- ?

In [1]:
methods(copy) # methods()...ある名前で定義されているメソッドを出力

# 44 methods for generic function "copy":
copy(e::Expr) in Base at expr.jl:35
copy(s1::IntSet) in Base at intset.jl:11
copy(o::ObjectIdDict) in Base at associative.jl:475
copy(src::Base.dSFMT.DSFMT_state) in Base.dSFMT at dSFMT.jl:32
copy(src::MersenneTwister) in Base.Random at random.jl:112
copy(vset::Base.Pkg.Types.VersionSet) in Base.Pkg.Types at pkg/types.jl:66
copy(a::Base.Pkg.Types.Available) in Base.Pkg.Types at pkg/types.jl:148
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:101
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuild) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:159
copy(a::Base.Pkg.Resolve.VersionWeights.VersionWeight) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:219
copy(a::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue) in Base.Pkg.Resolve.MaxSum.FieldValues at pkg/resolve/fieldvalue.jl:68
copy(r::Range) in Base at range.jl:430
copy(x::Number) in Base at number.jl:48
copy(a::T) where T<:Array in Base at array.jl:139
copy(M::SymTridiagonal) in Base.LinAlg at linalg/tridiag.jl:105
copy(M::Tridiagonal) in Base.LinAlg at linalg/tridiag.jl:517
copy(A::LowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitLowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::UpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitUpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Symmetric{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:160
copy(A::Hermitian{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:161
copy(M::Bidiagonal) in Base.LinAlg at linalg/bidiag.jl:266
copy(ra::Base.ReshapedArray{#s268,2,#s267,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where #s267<:SparseMatrixCSC where #s268) in Base.SparseArrays at sparse/sparsematrix.jl:238
copy(S::SparseMatrixCSC) in Base.SparseArrays at sparse/sparsematrix.jl:253
copy(A::Base.SparseArrays.CHOLMOD.Sparse{Tv}, stype::Integer, mode::Integer) where Tv<:Float64 in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:618
copy(A::Base.SparseArrays.CHOLMOD.Sparse) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1209
copy(x::AbstractSparseArray{Tv,Ti,1} where Ti where Tv) in Base.SparseArrays at sparse/sparsevector.jl:825
copy(A::Base.SparseArrays.CHOLMOD.Dense) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1208
copy(a::AbstractArray) in Base at abstractarray.jl:697
copy(d::Dict) in Base at dict.jl:134
copy(d::WeakKeyDict) in Base at weakkeydict.jl:49
copy(a::Associative) in Base at associative.jl:113
copy(s::Set) in Base at set.jl:41
copy(b::Base.AbstractIOBuffer) in Base at iobuffer.jl:81
copy(A::Base.LinAlg.LQ) in Base.LinAlg at linalg/lq.jl:48
copy(C::Base.LinAlg.Cholesky) in Base.LinAlg at linalg/cholesky.jl:416
copy(C::Base.LinAlg.CholeskyPivoted) in Base.LinAlg at linalg/cholesky.jl:417
copy(J::UniformScaling) in Base.LinAlg at linalg/uniformscaling.jl:41
copy(F::Base.LinAlg.Schur) in Base.LinAlg at linalg/schur.jl:288
copy(F::Base.LinAlg.GeneralizedSchur) in Base.LinAlg at linalg/schur.jl:289
copy(a::Base.Pkg.Resolve.VersionWeights.HierarchicalValue{T}) where T in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:71
copy(A::Base.SparseArrays.CHOLMOD.Factor) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1210
copy(md::MbedTLS.MD) in MbedTLS at /Users/U05284/.julia/v0.6/MbedTLS/src/md.jl:93

In [2]:
@which(copy([1, 2, 3])) # @which...どの引数の処理のメソッドが呼ばれているかを出力

copy(a::T) where T<:Array in Base at array.jl:139

In [3]:
fieldnames(Hermitian) # filednames()...インスタンスや構造体の中身のタイプを出力

2-element Array{Symbol,1}:
 :data
 :uplo

In [4]:
typeof([1;2;3]) # typeof()... 型を出力, c.f. ;は改行, つまりこれは列ベクトル

Array{Int64,1}

In [5]:
@code_lowered sin(sqrt(3)) # @code_lowered...どんな処理が発生してるかを確認できる. sqrt()は√3でもok.

CodeInfo(:(begin 
        nothing
        nothing
        SSAValue(0) = (Base.cconvert)(Base.Math.Float64, x)
        SSAValue(1) = $(Expr(:foreigncall, :((Core.tuple)("sin", Base.Math.libm)), Float64, svec(Float64), :((Base.unsafe_convert)(Base.Math.Float64, SSAValue(0))), SSAValue(0)))
        return (Base.Math.nan_dom_err)(SSAValue(1), x)
    end))

またIntractiveShellにてjuliaを使っている場合だけですが.コンソール時に"?"を打ち込むとhelpモードに入ります.

In [6]:
# ?copy...copyのヘルプが出ます

-----

## 2.Array
基本的な構文はmatlabと同じ.

### 宣言方法と代入方法

In [7]:
a = Vector{Float64}(5) #5つのfloat64値からなる一次元配列の生成
a = [1 2 3 4 5]

cv = [1;2;3;4;5] # 列ベクトル
rv = [1 2 3 4 5] # 行ベクトル

println(cv)
println(rv)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
a[3] = 100 # 配列aの"3つめ"の要素を100に変更. 線形indexを使用しています.
a

1×5 Array{Int64,2}:
 1  2  100  4  5

In [9]:
b = Matrix{Float64}(4,2) # size(4, 2)からなるFloat64型行列を生成

c = Array{Float64}(4,5,6,7) # (4,5,6,7)からなるFloat64配列

mat =  [11 12 13 14
        21 22 23 24
        31 32 33 34] # 直接inlineでMatrixの宣言も可能

3×4 Array{Int64,2}:
 11  12  13  14
 21  22  23  24
 31  32  33  34

In [10]:
mat[1,2] = 4 # 変更方法は同じ.
mat

3×4 Array{Int64,2}:
 11   4  13  14
 21  22  23  24
 31  32  33  34

#### memo1
> memo1: REPL環境を使ってる時, 評価された時に値を返される物の後ろに";"を入れると出力を無視できます.  
> memo2: arrayの値はメモリの場所へのポインタです.

In [11]:
#memo1
mat;

In [12]:
#memo2
a = [1;2;3]
b = a
b[1] = 10
println(a, b)

[10, 2, 3][10, 2, 3]


In [13]:
#memo2: aも一緒に変更されたくない場合は"copy"を使います.
a = [1;2;3]
b = copy(a)
b[1] = 10
println(a, b)

[1, 2, 3][10, 2, 3]


#### memo2
他にもコンストラクタを使わずにも宣言することが可能です. その場合以下のメソッドが有用.  
いずれも, 引数のArrayのsize/shapeを引き継いだ新しいArrayを返します.

- similar()
- zeros()
- ones()

In [14]:
simA = similar(a) # aと同じ構造の未初期化のaryを返す.
zerosA = zeros(a) # aと同じ構造の全て0のaryを返す.
onesA = ones(a) # aと同じ構造の全て1のaryを返す.

println(simA, zerosA, onesA)

[4469783144, 4469783576, 4469791928][0, 0, 0][1, 1, 1]


#### memo3
1) 配列は[a:b]によって切り出すことが可能.
- [a:b]...配列のa番目からb番目までを切り出す

2) また, aryにはどんな種類のtypeも内包できるため配列の中に配列を含めることももちろん可能です.


In [15]:
#1)
a = [1 2 3 4 5 6 7 8 9 10]
a[1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [16]:
# 2)
a = Vector{Vector{Float64}}(3)
a[1] = [1;2;3]
a[2] = [1;2]
a[3] = [3;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [1.0, 2.0]     
 [3.0, 4.0, 5.0]

また, 入れ子構造になったarrayのcopyにはdeepcopy()を使います.

In [17]:
b = deepcopy(a)
b[1] = [1;3;2]
println(a)
println(b)

Array{Float64,1}[[1.0, 2.0, 3.0], [1.0, 2.0], [3.0, 4.0, 5.0]]
Array{Float64,1}[[1.0, 3.0, 2.0], [1.0, 2.0], [3.0, 4.0, 5.0]]


#### memo4
高い実行速度を達成するためにはコード量を減らすことが重要です. 
そのため, Juliaには引数に破壊的代入をもたらすmutationメソッドがあり, そのようなメソッドの末尾には!が付いています.

In [18]:
# mutation method ex.
a = [1;6;9]
scale!(a, 2) # scale!(ary, scalar)...aryをscalar倍

3-element Array{Int64,1}:
  2
 12
 18

----

## 3.制御フロー

Juliaの制御フローは他のスクリプト言語と大して変化はなし.
いつも通りのfor loop, while, ifがあるくらい.

他のものはdocumentを参照.

In [19]:
# for loop
for i=1:5 #1:5でrange, =をinに変えても実行可能.
  println(i)
end

1
2
3
4
5


In [20]:
t = 0
while t < 5
  println(t)
  t+=1
end

0
1
2
3
4


In [21]:
symbol = :asdf

if symbol == :asdf
  println("you said asdf")
else
  println("no idea")
end

you said asdf
search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: end endof endswith ENDIAN_BOM send append! QuoteNode RangeIndex getindex



#### memo
Juliaのforloopで面白いのは, なんと多重for loopを一列で書ける

In [22]:
for i=1:5, j=2:4
  println(i*j)
end

2
3
4
4
6
8
6
9
12
8
12
16
10
15
20


### 練習問題
http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems
上5問.

制御flow理解できてれば実装できるはず.

#### Q1. (N,N)型で, 体格が-2, 体格の左右隣が1, それ以外が0の行列を作れ. ストラング行列っていうとか

In [62]:
N = 5
#mat = Matrix{Float64}(N, N)
mat = zeros(N, N)
for i=1:N, j=1:N
  if i==j
    mat[i,j] = -2
  elseif i==j+1||i==j-1
    mat[i,j] = 1
  end
end

mat

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

##### Q1. 綺麗なコードver. こっちの方が"juliaらしい"

In [71]:
N=5
A = zeros(N,N)
for i=1:N, j=1:N
  abs(i-j)==1 && (A[i,j]=1)
  i==j && (A[i,j]=-2)
end
A

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

#### Q2. 階上, my_factorial(n)で, n!を出力.

In [73]:
function my_factorial(n)
  ans = 1
  for i=1:n
    ans*=i
  end
  ans  
end
my_factorial(15)
#c.f. ただしこれでは大きい値を扱う形になった時にOverFlowが発生する.(ex. 30を入れるとnegativeになる)

1307674368000

##### こういう時は入力と出力の型を同じにすればよい. one(x)を使用する

In [75]:
function my_factorial(n)
  k = one(n) # one(x)...xと同じ型で値1の数値を返す.
  for i=1:n
    k *= i
  end
  k
end
my_factorial(big(30))

265252859812191058636308480000000

#### Q3.二項問題
nを試行回数, pを成功する確率とした時, n回の内成功した回数XをX=Bin(n,p)と表すとする.  
例えば, Bin(10, 0.5)の時, Xは10回コインを投げた時に表が出てくる回数に等しい.  
  
Xを返すbinomial_rv(n,p)をrand()を用いて実装せよ

In [76]:
function binomial_rv(n,p)
  k=0
  for i=1:n
    p<=rand() && (k+=1)
  end
  k
end

#check
[binomial_rv(10, 0.5) for i=1:5]

5-element Array{Int64,1}:
 5
 2
 3
 4
 5

#### Q4. モンテカルロによる円周率の計算
πを乱数を用いて近似せよ.

**Hint: モンテカルロ法**
[-1, 1]×[-1, 1]の四角形に内包される円があった時, *円の面積はπ*($πr^2$より), *四角形の面積は4*.  
そのため, 乱数を用いて[-1,1]×[-1,1]の部分に一様な乱数で点を打った時, *円周の中に打たれる確率はπ/4*($x^2+y^2$≦1より).  
これを用いてπの大体の値を求めよ.

In [140]:
function montecarlo(n)
  c = 0
  for _=1:n
    x, y = 2rand(2)-1
    sqrt(x^2+y^2)<=1 && (c+=1)
  end
  return 4c/n
end

montecarlo(10000000)

3.1420824

#### Q5. 時系列生成問題
AR1時系列は, $x_{t+1} = \alpha x_i + \epsilon_{t+1}$ では定義されたとする.  
この時それぞれ, $x_0$=0, t=0...T, ソケット$\epsilon_{t}$は独立同分布である(N(0,1)はrandn()によって与えられるとする).  
  
T=200の時,

- α=0
- α=0.5
- α=0.9

の場合のそれぞれのパラメータの時間変化をPlot.jlを用いて示せ.  
また, αの値を表す線にはplot関数にlabelオプションをつけ, ラベルせよ.

In [1]:
using Plots

function ar(T, alpha)
  x=zeros(T+1)
  x[1] = 0.0
  for t=1:T
    x[t+1] = alpha * x[t] + randn()
  end
  x
end

_ar (generic function with 1 method)

In [17]:
result = [ar(i) for i in [0.0,0.5,0.9]]

gr() # jupyer上でグラフを出力するには必要.
plot(result, label=["a=0", "a=0.5", "a=0.9"], lw=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 30 
 
 
 60 
 
 
 90 
 
 
 120 
 
 
 150 
 
 
 180 
 
 
 -2.5 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
<polyline clip-path="url(#clip9502)" style="stroke:#009af9; stroke-width:3; stroke-opacity:1; fill:none" points="
 39.3701,227.107 42.1339,203.658 44.8976,252.169 47.6614,259.035 50.4252,209.051 53.189,225.608 55.9528,215.949 58.7165,255.024 61.4803,210.509 64.2441,235.514 
 67.0079,188.172 69.7717,229.091 72.5354,250.748 75.2992,187.682 78.063,212.799 80.8268,214.257 83.5906,212.542 86.3543,240.91 89.1181,205.291 91.8819,213.928 
 94.6457,230.622 97.4094,219.372 100.173,218.147 102.937,195.316 105.701,188.565 108.465,220.048 111.228,174.255 113.992,255.97 116.756,184.583 119.52,192.848 
 122.283,229.913 125.047,251.836 127.811,238.389 130.575,210.141 133.339,228.276 136.102,257.184 138.866,271.052 141.63,208.153 144.394,248.453 147.157,230.441 
 149.921,255.768 152.685,251.627 155.449,212.002 158.213,262.47 160.976,167.544 163.74,254.889 166.504,198.42 169.268,219.105 172.031,226.141 174.795,171.211 
 177.559,208.256 180.323,184.016 183.087,226.423 185.85,235.742 188.614,224.583 191.378,268.619 194.142,181.635 196.906,208.818 199.669,240.846 202.433,202.288 
 205.197,194.972 207.961,222.019 210.724,201.863 213.488,241.18 216.252,202.074 219.016,184.336 221.78,218.679 224.543,221.52 227.307,192.956 230.071,222.127 
 232.835,230.164 235.598,200.3 238.362,213.175 241.126,288.797 243.89,230.58 246.654,223.681 249.417,219.468 252.181,203.42 254.945,226.771 257.709,165.751 
 260.472,219.123 263.236,270.067 266,206.134 268.764,219.75 271.528,256.948 274.291,200.672 277.055,199.797 279.819,211.804 282.583,240.472 285.346,224.839 
 288.11,251.008 290.874,228.553 293.638,179.859 296.402,224.274 299.165,186.053 301.929,230.407 304.693,239.452 307.457,216.141 310.22,204.638 312.984,244.47 
 315.748,239.62 318.512,255.831 321.276,236.12 324.039,221.9 326.803,204.769 329.567,261.52 332.331,189.065 335.094,179.565 337.858,221.208 340.622,189.093 
 343.386,218.241 346.15,242.724 348.913,221.87 351.677,209.554 354.441,250.321 357.205,225.326 359.969,150.225 362.732,233.995 365.496,219.919 368.26,254.571 
 371.024,231.25 373.787,235.605 376.551,219.077 379.315,211.245 382.079,217.293 384.843,210.569 387.606,234.359 390.37,161.351 393.134,201.33 395.898,254.526 
 398.661,249.647 401.425,205.023 404.189,235.818 406.953,173.312 409.717,214.588 412.48,182.996 415.244,230.921 418.008,228.657 420.772,239.12 423.535,235.829 
 426.299,210.028 429.063,196.52 431.827,237.498 434.591,218.568 437.354,286.854 440.118,240.698 442.882,200.45 445.646,227.162 448.409,219.791 451.173,270.271 
 453.937,206.321 456.701,232.921 459.465,264.9 462.228,264.81 464.992,208.705 467.756,208.364 470.52,216.459 473.283,225.936 476.047,292.68 478.811,176.207 
 481.575,240.537 484.339,234.5 487.102,224.343 489.866,242.487 492.63,216.354 495.394,245.782 498.157,223.232 500.921,220.463 503.685,198.369 506.449,218.002 
 509.213,200.577 511.976,192.757 514.74,218.418 517.504,221.515 520.268,245.541 523.031,243.963 525.795,204.338 528.559,246.45 531.323,231.366 534.087,232.972 
 536.85,246.799 539.614,242.272 542.378,268.574 545.142,251.507 547.906,242.237 550.669,191.458 553.433,234.192 556.197,213.895 558.961,209.043 561.724,232.268 
 564.488,235.354 567.252,243.411 570.016,260.44 572.78,184.667 575.543,241.357 578.307,238.125 581.071,123.312 583.835,228.01 586.598,184.067 589.362,204.936 
 592.126,219.116 
 "/>
<polyline clip-path="url(#clip9502)" style="stroke:#e26f46; stroke-width:3; stroke-opacity:1; fill:none" points="
 39.3701,227.107 42.1339,228.557 44.8976,247.743 47.6614,244.844 50.4252,230.1 53.189,224.11 55.9528,245.855 58.7165,196.714 61.4803,213.775 64.2441,223.202 
 67.0079,230.787 69.7717,224.952 72.5354,259.231 75.2992,234.019 78.063,212.715 80.8268,224.318 83.5906,199.014 86.3543,179.354 89.1181,250.482 91.8819,230.186 
 94.6457,272.7