# Basic Introduction to Julia
とりあえずJuliaに触ってみよう.
基本的なスクリプト言語と書き方は同じです.
なんて言ったって, use like python and run like c, ですし.

## see also here
 - https://docs.julialang.org/en/latest/
 - https://gitter.im/JuliaLang/julia
Generally, discussued Juylia0.6.2

## 1. 開発用ツール
Juliaにはたくさんのdocumentation toolがあるけどたくさんありすぎて紹介しきれないので, そのうちのいくつかを紹介.

Juliaのメソッドも名前と引数のセットで認識するため, 同じ名前のメソッドでも引数に応じた複数の処理を一つの名前のメソッドに定義できます.

- methods()
- @which
- fieldnames()
- typeof()
-  @code_lowered
- ?

In [1]:
methods(copy) # methods()...ある名前で定義されているメソッドを出力

# 44 methods for generic function "copy":
copy(e::Expr) in Base at expr.jl:35
copy(s1::IntSet) in Base at intset.jl:11
copy(o::ObjectIdDict) in Base at associative.jl:475
copy(src::Base.dSFMT.DSFMT_state) in Base.dSFMT at dSFMT.jl:32
copy(src::MersenneTwister) in Base.Random at random.jl:112
copy(vset::Base.Pkg.Types.VersionSet) in Base.Pkg.Types at pkg/types.jl:66
copy(a::Base.Pkg.Types.Available) in Base.Pkg.Types at pkg/types.jl:148
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:101
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuild) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:159
copy(a::Base.Pkg.Resolve.VersionWeights.VersionWeight) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:219
copy(a::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue) in Base.Pkg.Resolve.MaxSum.FieldValues at pkg/resolve/fieldvalue.jl:68
copy(r::Range) in Base at range.jl:430
copy(x::Number) in Base at number.jl:48
copy(a::T) where T<:Array in Base at array.jl:139
copy(M::SymTridiagonal) in Base.LinAlg at linalg/tridiag.jl:105
copy(M::Tridiagonal) in Base.LinAlg at linalg/tridiag.jl:517
copy(A::LowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitLowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::UpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitUpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Symmetric{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:160
copy(A::Hermitian{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:161
copy(M::Bidiagonal) in Base.LinAlg at linalg/bidiag.jl:266
copy(ra::Base.ReshapedArray{#s268,2,#s267,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where #s267<:SparseMatrixCSC where #s268) in Base.SparseArrays at sparse/sparsematrix.jl:238
copy(S::SparseMatrixCSC) in Base.SparseArrays at sparse/sparsematrix.jl:253
copy(A::Base.SparseArrays.CHOLMOD.Sparse{Tv}, stype::Integer, mode::Integer) where Tv<:Float64 in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:618
copy(A::Base.SparseArrays.CHOLMOD.Sparse) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1209
copy(x::AbstractSparseArray{Tv,Ti,1} where Ti where Tv) in Base.SparseArrays at sparse/sparsevector.jl:825
copy(A::Base.SparseArrays.CHOLMOD.Dense) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1208
copy(a::AbstractArray) in Base at abstractarray.jl:697
copy(d::Dict) in Base at dict.jl:134
copy(d::WeakKeyDict) in Base at weakkeydict.jl:49
copy(a::Associative) in Base at associative.jl:113
copy(s::Set) in Base at set.jl:41
copy(b::Base.AbstractIOBuffer) in Base at iobuffer.jl:81
copy(A::Base.LinAlg.LQ) in Base.LinAlg at linalg/lq.jl:48
copy(C::Base.LinAlg.Cholesky) in Base.LinAlg at linalg/cholesky.jl:416
copy(C::Base.LinAlg.CholeskyPivoted) in Base.LinAlg at linalg/cholesky.jl:417
copy(J::UniformScaling) in Base.LinAlg at linalg/uniformscaling.jl:41
copy(F::Base.LinAlg.Schur) in Base.LinAlg at linalg/schur.jl:288
copy(F::Base.LinAlg.GeneralizedSchur) in Base.LinAlg at linalg/schur.jl:289
copy(a::Base.Pkg.Resolve.VersionWeights.HierarchicalValue{T}) where T in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:71
copy(A::Base.SparseArrays.CHOLMOD.Factor) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1210
copy(md::MbedTLS.MD) in MbedTLS at /Users/U05284/.julia/v0.6/MbedTLS/src/md.jl:93

In [2]:
@which(copy([1, 2, 3])) # @which...どの引数の処理のメソッドが呼ばれているかを出力

copy(a::T) where T<:Array in Base at array.jl:139

In [3]:
fieldnames(Hermitian) # filednames()...インスタンスや構造体の中身のタイプを出力

2-element Array{Symbol,1}:
 :data
 :uplo

In [4]:
typeof([1;2;3]) # typeof()... 型を出力, c.f. ;は改行, つまりこれは列ベクトル

Array{Int64,1}

In [5]:
@code_lowered sin(sqrt(3)) # @code_lowered...どんな処理が発生してるかを確認できる. sqrt()は√3でもok.

CodeInfo(:(begin 
        nothing
        nothing
        SSAValue(0) = (Base.cconvert)(Base.Math.Float64, x)
        SSAValue(1) = $(Expr(:foreigncall, :((Core.tuple)("sin", Base.Math.libm)), Float64, svec(Float64), :((Base.unsafe_convert)(Base.Math.Float64, SSAValue(0))), SSAValue(0)))
        return (Base.Math.nan_dom_err)(SSAValue(1), x)
    end))

またIntractiveShellにてjuliaを使っている場合だけですが.コンソール時に"?"を打ち込むとhelpモードに入ります.

In [6]:
# ?copy...copyのヘルプが出ます

-----

## 2.Array
基本的な構文はmatlabと同じ.

### 宣言方法と代入方法

In [7]:
a = Vector{Float64}(5) #5つのfloat64値からなる一次元配列の生成
a = [1 2 3 4 5]

cv = [1;2;3;4;5] # 列ベクトル
rv = [1 2 3 4 5] # 行ベクトル

println(cv)
println(rv)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
a[3] = 100 # 配列aの"3つめ"の要素を100に変更. 線形indexを使用しています.
a

1×5 Array{Int64,2}:
 1  2  100  4  5

In [9]:
b = Matrix{Float64}(4,2) # size(4, 2)からなるFloat64型行列を生成

c = Array{Float64}(4,5,6,7) # (4,5,6,7)からなるFloat64配列

mat =  [11 12 13 14
        21 22 23 24
        31 32 33 34] # 直接inlineでMatrixの宣言も可能

3×4 Array{Int64,2}:
 11  12  13  14
 21  22  23  24
 31  32  33  34

In [10]:
mat[1,2] = 4 # 変更方法は同じ.
mat

3×4 Array{Int64,2}:
 11   4  13  14
 21  22  23  24
 31  32  33  34

#### memo1
> memo1: REPL環境を使ってる時, 評価された時に値を返される物の後ろに";"を入れると出力を無視できます.  
> memo2: arrayの値はメモリの場所へのポインタです.

In [11]:
#memo1
mat;

In [12]:
#memo2
a = [1;2;3]
b = a
b[1] = 10
println(a, b)

[10, 2, 3][10, 2, 3]


In [13]:
#memo2: aも一緒に変更されたくない場合は"copy"を使います.
a = [1;2;3]
b = copy(a)
b[1] = 10
println(a, b)

[1, 2, 3][10, 2, 3]


#### memo2
他にもコンストラクタを使わずにも宣言することが可能です. その場合以下のメソッドが有用.  
いずれも, 引数のArrayのsize/shapeを引き継いだ新しいArrayを返します.

- similar()
- zeros()
- ones()

In [14]:
simA = similar(a) # aと同じ構造の未初期化のaryを返す.
zerosA = zeros(a) # aと同じ構造の全て0のaryを返す.
onesA = ones(a) # aと同じ構造の全て1のaryを返す.

println(simA, zerosA, onesA)

[4469783144, 4469783576, 4469791928][0, 0, 0][1, 1, 1]


#### memo3
1) 配列は[a:b]によって切り出すことが可能.
- [a:b]...配列のa番目からb番目までを切り出す

2) また, aryにはどんな種類のtypeも内包できるため配列の中に配列を含めることももちろん可能です.


In [15]:
#1)
a = [1 2 3 4 5 6 7 8 9 10]
a[1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [16]:
# 2)
a = Vector{Vector{Float64}}(3)
a[1] = [1;2;3]
a[2] = [1;2]
a[3] = [3;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [1.0, 2.0]     
 [3.0, 4.0, 5.0]

また, 入れ子構造になったarrayのcopyにはdeepcopy()を使います.

In [17]:
b = deepcopy(a)
b[1] = [1;3;2]
println(a)
println(b)

Array{Float64,1}[[1.0, 2.0, 3.0], [1.0, 2.0], [3.0, 4.0, 5.0]]
Array{Float64,1}[[1.0, 3.0, 2.0], [1.0, 2.0], [3.0, 4.0, 5.0]]


#### memo4
高い実行速度を達成するためにはコード量を減らすことが重要です. 
そのため, Juliaには引数に破壊的代入をもたらすmutationメソッドがあり, そのようなメソッドの末尾には!が付いています.

In [18]:
# mutation method ex.
a = [1;6;9]
scale!(a, 2) # scale!(ary, scalar)...aryをscalar倍

3-element Array{Int64,1}:
  2
 12
 18

----

## 3.制御フロー

Juliaの制御フローは他のスクリプト言語と大して変化はなし.
いつも通りのfor loop, while, ifがあるくらい.

他のものはdocumentを参照.

In [19]:
# for loop
for i=1:5 #1:5でrange, =をinに変えても実行可能.
  println(i)
end

1
2
3
4
5


In [20]:
t = 0
while t < 5
  println(t)
  t+=1
end

0
1
2
3
4


In [21]:
symbol = :asdf

if symbol == :asdf
  println("you said asdf")
else
  println("no idea")
end

you said asdf
search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: end endof endswith ENDIAN_BOM send append! QuoteNode RangeIndex getindex



#### memo
Juliaのforloopで面白いのは, なんと多重for loopを一列で書ける

In [22]:
for i=1:5, j=2:4
  println(i*j)
end

2
3
4
4
6
8
6
9
12
8
12
16
10
15
20


### 練習問題
http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems
上四問.

In [62]:
#Q1. (N,N)型で, 体格が-2, 体格の左右隣が1, それ以外が0の行列を作れ.
N = 5
#mat = Matrix{Float64}(N, N)
mat = zeros(N, N)
for i=1:N, j=1:N
  if i==j
    mat[i,j] = -2
  elseif i==j+1||i==j-1
    mat[i,j] = 1
  end
end

mat

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

In [61]:
#Q1. 綺麗なコードver. こっちの方が"juliaらしい"
N=5
A = zeros(N,N)
for i=1:N, j=1:N
  abs(i-j)==1 && (A[i,j]=1)
  i==j && (A[i,j]=-2)
end
A

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

In [77]:
## Q2. 階上, my_factorial(n)で, n!を出力. (bonus無思考)
function my_factorial(n)
  ans = one(1)
  for i=1:n
    ans*=i
  end
  print(ans)
end

my_factorial(big(100))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000