# Basic Introduction to Julia
とりあえずJuliaに触ってみよう.
基本的なスクリプト言語と書き方は同じです.
なんて言ったって, use like python and run like c, ですし.

## see also here
 - https://docs.julialang.org/en/latest/
 - https://gitter.im/JuliaLang/julia
Generally, discussued Juylia0.6.2

## 1. 開発用ツール
Juliaにはたくさんのdocumentation toolがあるけどたくさんありすぎて紹介しきれないので, そのうちのいくつかを紹介.

Juliaのメソッドも名前と引数のセットで認識するため, 同じ名前のメソッドでも引数に応じた複数の処理を一つの名前のメソッドに定義できます.

- methods()
- @which
- fieldnames()
- typeof()
-  @code_lowered
- ?

In [1]:
methods(copy) # methods()...ある名前で定義されているメソッドを出力

# 44 methods for generic function "copy":
copy(e::Expr) in Base at expr.jl:35
copy(s1::IntSet) in Base at intset.jl:11
copy(o::ObjectIdDict) in Base at associative.jl:475
copy(src::Base.dSFMT.DSFMT_state) in Base.dSFMT at dSFMT.jl:32
copy(src::MersenneTwister) in Base.Random at random.jl:112
copy(vset::Base.Pkg.Types.VersionSet) in Base.Pkg.Types at pkg/types.jl:66
copy(a::Base.Pkg.Types.Available) in Base.Pkg.Types at pkg/types.jl:148
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:101
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuild) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:159
copy(a::Base.Pkg.Resolve.VersionWeights.VersionWeight) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:219
copy(a::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue) in Base.Pkg.Resolve.MaxSum.FieldValues at pkg/resolve/fieldvalue.jl:68
copy(r::Range) in Base at range.jl:430
copy(x::Number) in Base at number.jl:48
copy(a::T) where T<:Array in Base at array.jl:139
copy(M::SymTridiagonal) in Base.LinAlg at linalg/tridiag.jl:105
copy(M::Tridiagonal) in Base.LinAlg at linalg/tridiag.jl:517
copy(A::LowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitLowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::UpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitUpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Symmetric{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:160
copy(A::Hermitian{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:161
copy(M::Bidiagonal) in Base.LinAlg at linalg/bidiag.jl:266
copy(ra::Base.ReshapedArray{#s268,2,#s267,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where #s267<:SparseMatrixCSC where #s268) in Base.SparseArrays at sparse/sparsematrix.jl:238
copy(S::SparseMatrixCSC) in Base.SparseArrays at sparse/sparsematrix.jl:253
copy(A::Base.SparseArrays.CHOLMOD.Sparse{Tv}, stype::Integer, mode::Integer) where Tv<:Float64 in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:618
copy(A::Base.SparseArrays.CHOLMOD.Sparse) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1209
copy(x::AbstractSparseArray{Tv,Ti,1} where Ti where Tv) in Base.SparseArrays at sparse/sparsevector.jl:825
copy(A::Base.SparseArrays.CHOLMOD.Dense) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1208
copy(a::AbstractArray) in Base at abstractarray.jl:697
copy(d::Dict) in Base at dict.jl:134
copy(d::WeakKeyDict) in Base at weakkeydict.jl:49
copy(a::Associative) in Base at associative.jl:113
copy(s::Set) in Base at set.jl:41
copy(b::Base.AbstractIOBuffer) in Base at iobuffer.jl:81
copy(A::Base.LinAlg.LQ) in Base.LinAlg at linalg/lq.jl:48
copy(C::Base.LinAlg.Cholesky) in Base.LinAlg at linalg/cholesky.jl:416
copy(C::Base.LinAlg.CholeskyPivoted) in Base.LinAlg at linalg/cholesky.jl:417
copy(J::UniformScaling) in Base.LinAlg at linalg/uniformscaling.jl:41
copy(F::Base.LinAlg.Schur) in Base.LinAlg at linalg/schur.jl:288
copy(F::Base.LinAlg.GeneralizedSchur) in Base.LinAlg at linalg/schur.jl:289
copy(a::Base.Pkg.Resolve.VersionWeights.HierarchicalValue{T}) where T in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:71
copy(A::Base.SparseArrays.CHOLMOD.Factor) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1210
copy(md::MbedTLS.MD) in MbedTLS at /Users/U05284/.julia/v0.6/MbedTLS/src/md.jl:93

In [2]:
@which(copy([1, 2, 3])) # @which...どの引数の処理のメソッドが呼ばれているかを出力

copy(a::T) where T<:Array in Base at array.jl:139

In [3]:
fieldnames(Hermitian) # filednames()...インスタンスや構造体の中身のタイプを出力

2-element Array{Symbol,1}:
 :data
 :uplo

In [4]:
typeof([1;2;3]) # typeof()... 型を出力, c.f. ;は改行, つまりこれは列ベクトル

Array{Int64,1}

In [5]:
@code_lowered sin(sqrt(3)) # @code_lowered...どんな処理が発生してるかを確認できる. sqrt()は√3でもok.

CodeInfo(:(begin 
        nothing
        nothing
        SSAValue(0) = (Base.cconvert)(Base.Math.Float64, x)
        SSAValue(1) = $(Expr(:foreigncall, :((Core.tuple)("sin", Base.Math.libm)), Float64, svec(Float64), :((Base.unsafe_convert)(Base.Math.Float64, SSAValue(0))), SSAValue(0)))
        return (Base.Math.nan_dom_err)(SSAValue(1), x)
    end))

またIntractiveShellにてjuliaを使っている場合だけですが.コンソール時に"?"を打ち込むとhelpモードに入ります.

In [6]:
# ?copy...copyのヘルプが出ます

-----

## 2.Array
基本的な構文はmatlabと同じ.

### 宣言方法と代入方法

In [7]:
a = Vector{Float64}(5) #5つのfloat64値からなる一次元配列の生成
a = [1 2 3 4 5]

cv = [1;2;3;4;5] # 列ベクトル
rv = [1 2 3 4 5] # 行ベクトル

println(cv)
println(rv)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
a[3] = 100 # 配列aの"3つめ"の要素を100に変更. 線形indexを使用しています.
a

1×5 Array{Int64,2}:
 1  2  100  4  5

In [9]:
b = Matrix{Float64}(4,2) # size(4, 2)からなるFloat64型行列を生成

c = Array{Float64}(4,5,6,7) # (4,5,6,7)からなるFloat64配列

mat =  [11 12 13 14
        21 22 23 24
        31 32 33 34] # 直接inlineでMatrixの宣言も可能

3×4 Array{Int64,2}:
 11  12  13  14
 21  22  23  24
 31  32  33  34

In [10]:
mat[1,2] = 4 # 変更方法は同じ.
mat

3×4 Array{Int64,2}:
 11   4  13  14
 21  22  23  24
 31  32  33  34

#### memo1
> memo1: REPL環境を使ってる時, 評価された時に値を返される物の後ろに";"を入れると出力を無視できます.  
> memo2: arrayの値はメモリの場所へのポインタです.

In [11]:
#memo1
mat;

In [12]:
#memo2
a = [1;2;3]
b = a
b[1] = 10
println(a, b)

[10, 2, 3][10, 2, 3]


In [13]:
#memo2: aも一緒に変更されたくない場合は"copy"を使います.
a = [1;2;3]
b = copy(a)
b[1] = 10
println(a, b)

[1, 2, 3][10, 2, 3]


#### memo2
他にもコンストラクタを使わずにも宣言することが可能です. その場合以下のメソッドが有用.  
いずれも, 引数のArrayのsize/shapeを引き継いだ新しいArrayを返します.

- similar()
- zeros()
- ones()

In [14]:
simA = similar(a) # aと同じ構造の未初期化のaryを返す.
zerosA = zeros(a) # aと同じ構造の全て0のaryを返す.
onesA = ones(a) # aと同じ構造の全て1のaryを返す.

println(simA, zerosA, onesA)

[4469783144, 4469783576, 4469791928][0, 0, 0][1, 1, 1]


#### memo3
1) 配列は[a:b]によって切り出すことが可能.
- [a:b]...配列のa番目からb番目までを切り出す

2) また, aryにはどんな種類のtypeも内包できるため配列の中に配列を含めることももちろん可能です.


In [15]:
#1)
a = [1 2 3 4 5 6 7 8 9 10]
a[1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [16]:
# 2)
a = Vector{Vector{Float64}}(3)
a[1] = [1;2;3]
a[2] = [1;2]
a[3] = [3;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [1.0, 2.0]     
 [3.0, 4.0, 5.0]

また, 入れ子構造になったarrayのcopyにはdeepcopy()を使います.

In [17]:
b = deepcopy(a)
b[1] = [1;3;2]
println(a)
println(b)

Array{Float64,1}[[1.0, 2.0, 3.0], [1.0, 2.0], [3.0, 4.0, 5.0]]
Array{Float64,1}[[1.0, 3.0, 2.0], [1.0, 2.0], [3.0, 4.0, 5.0]]


#### memo4
高い実行速度を達成するためにはコード量を減らすことが重要です. 
そのため, Juliaには引数に破壊的代入をもたらすmutationメソッドがあり, そのようなメソッドの末尾には!が付いています.

In [18]:
# mutation method ex.
a = [1;6;9]
scale!(a, 2) # scale!(ary, scalar)...aryをscalar倍

3-element Array{Int64,1}:
  2
 12
 18

----

## 3.制御フロー

Juliaの制御フローは他のスクリプト言語と大して変化はなし.
いつも通りのfor loop, while, ifがあるくらい.

他のものはdocumentを参照.

In [19]:
# for loop
for i=1:5 #1:5でrange, =をinに変えても実行可能.
  println(i)
end

1
2
3
4
5


In [20]:
t = 0
while t < 5
  println(t)
  t+=1
end

0
1
2
3
4


In [21]:
symbol = :asdf

if symbol == :asdf
  println("you said asdf")
else
  println("no idea")
end

you said asdf
search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: end endof endswith ENDIAN_BOM send append! QuoteNode RangeIndex getindex



#### memo
Juliaのforloopで面白いのは, なんと多重for loopを一列で書ける

In [22]:
for i=1:5, j=2:4
  println(i*j)
end

2
3
4
4
6
8
6
9
12
8
12
16
10
15
20


### 練習問題
http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems
上5問.

制御flow理解できてれば実装できるはず.

#### Q1. (N,N)型で, 体格が-2, 体格の左右隣が1, それ以外が0の行列を作れ. ストラング行列っていうとか

In [62]:
N = 5
#mat = Matrix{Float64}(N, N)
mat = zeros(N, N)
for i=1:N, j=1:N
  if i==j
    mat[i,j] = -2
  elseif i==j+1||i==j-1
    mat[i,j] = 1
  end
end

mat

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

##### Q1. 綺麗なコードver. こっちの方が"juliaらしい"

In [71]:
N=5
A = zeros(N,N)
for i=1:N, j=1:N
  abs(i-j)==1 && (A[i,j]=1)
  i==j && (A[i,j]=-2)
end
A

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

#### Q2. 階上, my_factorial(n)で, n!を出力.

In [73]:
function my_factorial(n)
  ans = 1
  for i=1:n
    ans*=i
  end
  ans  
end
my_factorial(15)
#c.f. ただしこれでは大きい値を扱う形になった時にOverFlowが発生する.(ex. 30を入れるとnegativeになる)

1307674368000

##### こういう時は入力と出力の型を同じにすればよい. one(x)を使用する

In [75]:
function my_factorial(n)
  k = one(n) # one(x)...xと同じ型で値1の数値を返す.
  for i=1:n
    k *= i
  end
  k
end
my_factorial(big(30))

265252859812191058636308480000000

#### Q3.二項問題
nを試行回数, pを成功する確率とした時, n回の内成功した回数XをX=Bin(n,p)と表すとする.  
例えば, Bin(10, 0.5)の時, Xは10回コインを投げた時に表が出てくる回数に等しい.  
  
Xを返すbinomial_rv(n,p)をrand()を用いて実装せよ

In [76]:
function binomial_rv(n,p)
  k=0
  for i=1:n
    p<=rand() && (k+=1)
  end
  k
end

#check
[binomial_rv(10, 0.5) for i=1:5]

5-element Array{Int64,1}:
 5
 2
 3
 4
 5

#### Q4. モンテカルロによる円周率の計算
πを乱数を用いて近似せよ.

**Hint: モンテカルロ法**
[-1, 1]×[-1, 1]の四角形に内包される円があった時, *円の面積はπ*($πr^2$より), *四角形の面積は4*.  
そのため, 乱数を用いて[-1,1]×[-1,1]の部分に一様な乱数で点を打った時, *円周の中に打たれる確率はπ/4*($x^2+y^2$≦1より).  
これを用いてπの大体の値を求めよ.

In [140]:
function montecarlo(n)
  c = 0
  for _=1:n
    x, y = 2rand(2)-1
    sqrt(x^2+y^2)<=1 && (c+=1)
  end
  return 4c/n
end

montecarlo(10000000)

3.1420824

#### Q5. 時系列生成問題
AR1時系列は, $x_{t+1} = \alpha x_i + \epsilon_{t+1}$ では定義されたとする.  
この時それぞれ, $x_0$=0, t=0...T, ソケット$\epsilon_{t}$は独立同分布である(N(0,1)はrandn()によって与えられるとする).  
  
T=200の時,

- α=0
- α=0.5
- α=0.9

の場合のそれぞれのパラメータの時間変化をPlot.jlを用いて示せ.  
また, αの値を表す線にはplot関数にlabelオプションをつけ, ラベルせよ.

In [5]:
using Plots

function ar(T, alpha)
  x=zeros(T+1)
  x[1] = 0.0
  for t=1:T
    x[t+1] = alpha * x[t] + randn()
  end
  x
end

ar (generic function with 1 method)

In [8]:
result = [ar(200, i) for i in [0.0,0.5,0.9]]

gr() # jupyer上でグラフを出力するには必要.
plot(result, label=["a=0", "a=0.5", "a=0.9"], lw=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 30 
 
 
 60 
 
 
 90 
 
 
 120 
 
 
 150 
 
 
 180 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
<polyline clip-path="url(#clip3002)" style="stroke:#009af9; stroke-width:3; stroke-opacity:1; fill:none" points="
 39.3701,229.533 42.1339,261.843 44.8976,276.464 47.6614,274.024 50.4252,274.05 53.189,205.429 55.9528,258.353 58.7165,269.537 61.4803,206.221 64.2441,233.87 
 67.0079,217.96 69.7717,247.002 72.5354,235.019 75.2992,210.669 78.063,256.491 80.8268,282.164 83.5906,273.149 86.3543,273.568 89.1181,238.368 91.8819,200.642 
 94.6457,228.655 97.4094,269.739 100.173,298.359 102.937,197.182 105.701,158.532 108.465,236.935 111.228,219.288 113.992,212.971 116.756,260.988 119.52,192.612 
 122.283,227.926 125.047,228.65 127.811,294.762 130.575,141.977 133.339,262.57 136.102,197.207 138.866,213.282 141.63,241.403 144.394,195.313 147.157,208.841 
 149.921,244.714 152.685,163.599 155.449,224.716 158.213,242.352 160.976,258.846 163.74,210.671 166.504,247.259 169.268,207.99 172.031,169.089 174.795,175.414 
 177.559,226.545 180.323,207.981 183.087,234.612 185.85,190.858 188.614,211.744 191.378,255.786 194.142,191.318 196.906,288.603 199.669,287.126 202.433,303.509 
 205.197,215.68 207.961,279.022 210.724,204.267 213.488,257.114 216.252,321.718 219.016,239.605 221.78,311.168 224.543,247.154 227.307,268.717 230.071,225.772 
 232.835,209.816 235.598,207.114 238.362,204.134 241.126,286.342 243.89,224.659 246.654,231.343 249.417,221.289 252.181,253.149 254.945,193.223 257.709,302.962 
 260.472,174.747 263.236,200.115 266,197.98 268.764,287.952 271.528,190.251 274.291,226.29 277.055,280.098 279.819,188.392 282.583,278.966 285.346,194.678 
 288.11,257.582 290.874,259.679 293.638,285.561 296.402,251.117 299.165,133.934 301.929,208.745 304.693,217.94 307.457,194.252 310.22,208.716 312.984,247.209 
 315.748,226.234 318.512,220.532 321.276,165.717 324.039,247.112 326.803,237.033 329.567,249.409 332.331,216.716 335.094,223.908 337.858,228.068 340.622,258.174 
 343.386,219.903 346.15,199.824 348.913,227.326 351.677,215.001 354.441,229.251 357.205,173.6 359.969,220.769 362.732,198.24 365.496,212.56 368.26,224.224 
 371.024,272.375 373.787,252.333 376.551,305.791 379.315,272.126 382.079,211.957 384.843,232.778 387.606,257.277 390.37,223.446 393.134,232.853 395.898,238.29 
 398.661,204.038 401.425,248.507 404.189,207.969 406.953,205.59 409.717,268.083 412.48,276.657 415.244,184.898 418.008,216.244 420.772,207.538 423.535,190.611 
 426.299,237.551 429.063,224.173 431.827,253.059 434.591,269.233 437.354,271.111 440.118,234.255 442.882,233.629 445.646,249.234 448.409,309.965 451.173,188.581 
 453.937,255.332 456.701,236.623 459.465,250.569 462.228,216.848 464.992,192.469 467.756,229.412 470.52,248.887 473.283,231.7 476.047,199.685 478.811,210.567 
 481.575,247.414 484.339,165.646 487.102,223.675 489.866,240.455 492.63,251.661 495.394,134.605 498.157,212.372 500.921,256.867 503.685,172.849 506.449,177.543 
 509.213,238.592 511.976,249.478 514.74,211.912 517.504,145.909 520.268,247.42 523.031,218.787 525.795,189.767 528.559,257.964 531.323,290.853 534.087,244.034 
 536.85,199.634 539.614,286.098 542.378,216.912 545.142,188.971 547.906,189.398 550.669,234.097 553.433,290.01 556.197,250.671 558.961,298.372 561.724,163.367 
 564.488,202.773 567.252,245.683 570.016,232.109 572.78,233.947 575.543,296.163 578.307,228.583 581.071,223.436 583.835,260.076 586.598,215.533 589.362,233.923 
 592.126,217.897 
 "/>
<polyline clip-path="url(#clip3002)" style="stroke:#e26f46; stroke-width:3; stroke-opacity:1; fill:none" points="
 39.3701,229.533 42.1339,253.078 44.8976,284.343 47.6614,247.271 50.4252,249.317 53.189,192.707 55.9528,240.47 58.7165,232.971 61.4803,198.433 64.2441,250.569 
 67.0079,228.209 69.7717,195.424 72.5354,220.677 75.2992,170.365 78.063,159.692 80.8268,144.923 83.5906,178.345 86.3543,203.498 89.1181,199.882 91.8819,199.91

## 関数
Juliaにはinlineとfunctionを使う2種類の方法があります.  
通常, Juliaの関数は関数の中で最後に評価された値を返します.

In [15]:
# inline
f(x,y) = 2x + y

# long form using "function"
function f(x)
  x+2
end

# 関数呼び出し
f(3,2) |> println
f(2) |> println

8
4


### 多重ディスパッチ
ここでポイントになるのはjuliaのコアな機能の一つである多重ディスパッチです. "一つの関数"であるfに２つのメソッドが存在することがわかるでしょうか. (juliaでは実行可能な関数の部分をメソッドと言います.  
ここではf(::Any,::Any)と, f(::Any)の２つのメソッドが定義されており, この場合関数fに与える引数の個数によりどちらが呼ばれるか決定します.  
  
またJuliaでは型に対応する::Typeの記号を用いることで型にも対応した多重ディスパッチを作ることができます.  
複数のメソッドを呼び出せる関数の呼び出し方をした場合, より厳密に定義されたメソッドが優先的に呼びだされます.

In [16]:
f(x::Int, y::Int) = 3x+2y

f(2,3) |> println # 3x+2y
f(2.0, 3) |> println # 2x+y, ::IntにマッチしないFloatのため.

12
7.0


In [19]:
f{T<:Number}(x::T, y::T) = 4x+10y

f(2,3) |> println # 3x+2y...より厳密に定義されている方なので.
f(2.0, 3.0) |> println # 4x+10y

12
38.0


> note: 型指定の変数化は可能な限り多くの型を含もうとするので, 親の型を明示的に宣言する必要がありません.  
> 例えば, xが数字で, yとzが同じ型の時にmatchするメソッドはこう書きます.

In [20]:
f{T<:Number, T2}(x::T,y::T2,z::T2) = 5x+ 5y+ 5z

f (generic function with 5 methods)

多重ディスパッチはJuliaのコアデザインのため, 後ほどより深く確認していきます.  
特にJuliaの関数は引数の型に応じたメソッド呼び出しの部分に特化しています.  
これは, fの呼び出し可能なメソッドがそれぞれバラバラにコンパイルされることを示していて, 最初に呼ばれたタイミングでコンパイルする仕組み担っていることを意味します.

### 確認問題
というのを意識してこの挙動を確認していきましょう.

In [21]:
f(x,y,z,w) = z+y+z+w
@time f(1,1,1,1)
@time f(1,1,1,1)
@time f(1,1,1,1)
@time f(1,1,1,1.0)
@time f(1,1,1,1.0)

  0.002164 seconds (381 allocations: 21.010 KB)
  0.000001 seconds (4 allocations: 160 bytes)
  0.000001 seconds (3 allocations: 144 bytes)
  0.002586 seconds (1.01 k allocations: 52.800 KB)
  0.000001 seconds (5 allocations: 176 bytes)


4.0

めっちゃはやい()

----

### 関数の他の便利機能
ひとつの関数にまとめて説明.

In [32]:
function test_func(x,y;z=0) # ;XXXでオプション引数. zはオプション引数. デフォ値0
  if z==0
    return x+y, x*y # return時点で関数終了. returnで戻り地設定. 複数値を返すことも可能. tupleで返される.
  else
    return x*y*z, x+y+z
  end
end

test_func (generic function with 2 methods)

In [33]:
x,y = test_func(1,2)

(3,2)

In [35]:
x,y = test_func(1,2;z=3)

(6,6)

In [ ]:
またJuliaの関数は第一級関数なので, 型の一種です.  
そのため, クロージャ等の関数型プログラムライクなことも可能です.  

In [36]:
function func_playtime(x) #zはオプション引数.
  y = 2+x
  function test()
    2y # Juliaの関数スコープ上, 一段回上のスコープで宣言されているものは参照することが可能です.
  end
  z = test() * test()
  return z,test
end
z, test = func_playtime(2)

(64,test)

In [37]:
test()

8

test()に対しyを指定したわけではありませんが, yの値をtest()は持っているのが解ると思います.  
これは, 関数スコープのルール上, 内側の関数は関数として宣言されている同じスコープの変数を参照することが可能だからです.  
これは自己参照のリカーシブ的な挙動であり, トップレベルのスコープというものがグローバルスコープということが予想できるかと思います.  

In [38]:
a = 2

2

これはグローバル変数です.　　
後ほど詳しく見ていきましょう.  
  
最後に, 無名関数の宣言で終わりましょう. 

In [39]:
g = (x,y) -> 2x+y

(::#7) (generic function with 1 method)

名前付き関数と違って, gは何度でも上書きすることが可能です.

In [40]:
g = (x) -> 2x

(::#9) (generic function with 1 method)

無名関数は多重ディスパッチに対応していません. が, v0.5からは名前付き関数同様にコンパイルするようになったため, 速度やパフォーマンスに差はありません.  

また, 関数のカリー化は

In [43]:
g = (x,y) -> 2x+y
h(x) = (y) -> g(x, y)
h(1)(2)

4

と書くことが可能です. 無名関数の応用ですね.

## 型宣言
Juliaで呼ぶ型とは, 他の言語で言うオブジェクトに相当します. (オブジェクトとはJuliaにとっては外様のコンセプト, 名前のついたコンポーネントを持つ型の物とするのであればの話ですが  
型の考えというのは, それが何であるかを示しており, 一方で型のインスタンス化というものは独自のものです.  
例えば, 製造者とモデルの譲歩兎を持つcar型を考えてみた時, トヨタRAV4はcar型のインスタンス化です.  
  
Juliaでは, 以下のようにcarの型を定義してインスタンス化することができます.

In [45]:
type Car
  make
  model
end

mycar = Car("Toyota", "Rav4")

Car("Toyota","Rav4")

あ, そういえばいい忘れましたが, Juliaでは文字列型を"..."で表します. まぁ普通の言語なら問題ないですよね??? (MATLABてめぇ聞いてるか???)　c.f.原文通りです  
typeのフィールドには"."シンタックスを使うことでアクセスが可能です.  

In [46]:
mycar.make

"Toyota"

もしJuliaのパフォーマンスを向上させたいのであれば, 一般的にまずやることはtype宣言を厳密にすることです.  
nameとfieldの属性を持つWorkshopParticipant型(型はキャメルケース)を宣言しようとしたら, この場合

In [48]:
type WorkshopParticipant
  name::String
  field::Symbol #シンボル型, 細かい型に関しては後述
end
tony = WorkshopParticipant("Tony", :physics)

WorkshopParticipant("Tony",:physics)

関数と同様に, typeは変数を用いて型を厳密にすることも可能です. 例えば, StaffMemberという名前とフィールドと年をプロパティに持った型は...

In [49]:
type StaffMember{T<:Number}
  name::String
  field::Symbol
  age::T
end

ter = StaffMember("Terry", :football, 17)

StaffMember{Int64}("Terry",:football,17)

変数を用いたtype宣言のルールは関数と同じです.  

> note: 殆どのネイティブで定義されているJuliaの型(float64やInt等)はこの方法で定義されています.  
> これはつまるところ, ユーザが宣言する型には制限がないということです.  
> 実際, プロトタイプのパッケージがBaseの中に動かされる前までは, たくさんのJuliaの機能のほとんどが最初にこの方法で出発しています.
  
最後に, 抽象型の紹介で終わりましょう. 抽象型はインスタンスにすることはできませんが, 型の木構造を作るためによく使われます.  
今までに出てきたNumber型も抽象型の一つです. 抽象型の宣言はAbstractキーワードを用いて作成します.

In [50]:
abstract Person

type Student <: Person
  name::String
  grade::Number
end

木構造の美しい作り方についてはこちらをご覧くださいませ.  
https://docs.julialang.org/en/release-0.5/manual/types/#abstract-types
  
抽象型の抽象型なども同様に作ることが可能です.

In [51]:
abstract AbstractStudent <: Person

supertype/subtypesを用いる事でtypeの構造を詳しく見ることも可能です.

In [59]:
Person |> subtypes |> println
Student |> supertype |> println

Any[AbstractStudent,Student]
Person


他のバージョンの型の一つに"immutable"というものがあります.  
immutableを使用すると, 型のフィールドの変数の型は変更不可能になります.  
しかし, Juliaは自動的にimmutable型はstackに初期化され, 一方で通常の型はheapで初期化されます.  
これは一般に, immutable型のほうがよりCPUの近くに保存でき, メモリアクセスのコストが低いということを示しています.
多くのJuliaのビルトイン型についてはパフォーマンスを意識しているためimmutableを用いtえ定義されています.

In [60]:
immutable Field
  name
  school
end

ds = Field(:DataScience, [:PhysicalScience, :ComputerScience])

Field(:DataScience,Symbol[:PhysicalScience,:ComputerScience])

### 確認問題
immutableの値に対しては非常に面白い現象を見ることができます. ds.nameとds.schoolは当たり前ですが変更できません. 理由がわかりますか?

In [61]:
ds.name  = :ComutationalStatics

LoadError: type Field is immutable

しかし, この処理は認められます.

In [63]:
push!(ds.school, :BiologicalScience)

3-element Array{Symbol,1}:
 :PhysicalScience  
 :ComputerScience  
 :BiologicalScience

> Hint: ポインタ

-----

Juliaでの一つの重要なことは, 全てのものは型であり, コードすらexpression型に当てはまります.(後述)  
そのため, フィールドにアクセスすることができる関数も同じく型です.  
  
すべての物はコンパイルさっるとCになるだけではなく, すべてのCパーツは常にアクセス可能です.  
例えば, 関数のポインタなんてのも

In [64]:
foo(x) = 2x
first(methods(foo)).lambda_template.fptr

Ptr{Void} @0x0000000000000000

## 基本的な型
Juliaにはたくさんの基本的な型が用意されています. 実際, 型による多重ディスパッチシステムとしてのジュリアを見るにそのコアデザインに関数と型のインタラクションがあることに気づくでしょう.　　

### 遅延評価型
MATLABやパイソンがArrayを組むために簡単な関数を用意しているにもかかわらず, Juliaには特別に作られた型を利用して, 実際の"array"を避ける傾向があります.  
ひとつの例は"Range"です. rangeを定義するためには,
> start:stepsize:end

で定義します.　

In [82]:
a = 1:5 
a |> println
b = 1:2:10 
b |> println

1:5
1:2:9


こいつらはarrayと同じように使えます

In [73]:
a[2] |> println
b[3] |> println

2
5


この場合, bの詳しいところを見ていきましょう.  

In [78]:
a |> typeof |> println
b |> typeof |> println

UnitRange{Int64}
StepRange{Int64,Int64}


bはarrayではなく, StepRange型であるようです.  
StepRangeは自身のフィールドを諒してarrayのように振る舞うことができます

In [75]:
fieldnames(StepRange)

3-element Array{Symbol,1}:
 :start
 :step 
 :stop 

> note: collect()を用いることで, どんな時でもStepRange等の型からArrayを取り出すことができます.

In [81]:
c = collect(a)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

遅延評価型が好まれる理由としては, 本当に必要になるまで計算をしないので, 処理を圧迫しないということです.  
@timeを使ってみてみましょう.

In [85]:
@time a = 1:100000
@time a = 1:100
@time b = collect(1:100000);

  0.000004 seconds (5 allocations: 192 bytes)
  0.000003 seconds (5 allocations: 192 bytes)
  0.000354 seconds (8 allocations: 781.547 KB)


ここでrangeが要する時間は非常に短いということがわかるでしょう.  
だいたいの理由としては, メモリのallocationの回数を大幅に落としているからです.  
StepRangeの場合, インスタンスが作成された時点ではたったの３つの数しか保持していません.  
しかし, bは100000この数を所有しており, rangeとaryの大きな違いを示しています.

### Dictionary
他の一般型の一つにDictionaryがあります.  
key-valueを用いてアクセスします.

In [89]:
d = Dict(:test=>2, "silly"=>:suit)
d[:test] |> println
d["silly"] |> println

2
suit


### Tuples
Tupleは変更不可なimmutableな配列です. めちゃくちゃ早いです.  
(x,y,z,....)で表すことが可能で, ひとつ以上の戻り値を持つ関数は自動的にtupleが戻り値になります.

In [92]:
tup = (2.,3) # typeを一致させる必要はありません.
x,y = (3., "hi") # tupleから複数の変数に分けることが可能です.

(3.0,"hi",1)

## 問題
http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems  
8~10を解く

Q8. 統計問題

In [101]:
#### 与えられるデータ #####
X = rand(1000, 3)
a0 = rand(3)
y = X * a0 + 0.1 * randn(1000)

##### Q9で使うデータ #####
X = rand(100)
y = 2X + 0.1 * randn(100);

randn(N,3)で与えられtあN×3のArrayと, 結果データが入ったN×1のデータがあったとします.

行列Xを生成する

## メタプログラミング
メタプログラミングはJuliaのでかい機能の一つです. キーとなる考えはJuliaのすべての文はExpression型であるというところです.  
JuliaはExpressionから抽象構文木(AST)を作成します. 実は前出てきたsymbolの部分で少し触れています.  
SymbolはASTの一部分で, これはパースなどで使われる構造です.  
一つの面白いSymbolの比較点は, 例によって文字列の比較点O(n)の一部であるO(1)と関数の表記であるマクロ(@を用いた特殊な関数の表記方法)

故にここまで来たらメタプログラミングをプログラムコードとアウトプットを取り入れるプログラミングであると認識できるでしょう.  
一般的な例としては**"time"**マクロです.

In [1]:
macro my_time(ex)
  return quote
    local t0 = time()
    local val = $ex
    local t1 = time()
    println("elapsed time: ", t1-t0, "seconds")
    val
  end
end

@my_time (macro with 1 method)

exを定義しているこの文章は評価する前と評価したあとの時間を取得して, その間の経過時間を出力します.   
(c.f. 実時間のマクロは今まで見てきたものと同様にアロケーションも計算してくれます)  
  
> Note: $exはmacroの中に表記を補完します. メタプログラミングの詳細にたどるためには通常のプログラム方法とは全く違った考え方をしなくてはならず説明に時間がかかるため, 次回のセッションで扱います.  
  
Q. なぜマクロ?  
A. ひとつの理由はあなたが求めるどんな文法も定義できるからです.  
メタプログラミングはカッら自身の表記を操作するため, どのように動くコードに表記がパースされるかを知る限り, どんな文法でもあなたの文法にすることができます.  
後ほどケーススタディについては扱います.  
また, 別の理由としては, パースするタイミングで実行され, 関数がコンパイルするよりも前に一度だけ呼ばれるからです.

### Juliaのパースと実行の順番について
1. パースの後の抽象高分岐(AST) <- Macro
2. loweringの後のASt <- @code_typed
3. 最適化と型推論の後のAST <- Generated Functions(@code_lowered
4. LLVM IR <- Functions(@code_llvm
5. アセンブリ <- @code_native