# Basic Introduction to Julia
とりあえずJuliaに触ってみよう.
基本的なスクリプト言語と書き方は同じです.
なんて言ったって, use like python and run like c, ですし.

## see also here
 - https://docs.julialang.org/en/latest/
 - https://gitter.im/JuliaLang/julia
Generally, discussued Juylia0.6.2

## 1. 開発用ツール
Juliaにはたくさんのdocumentation toolがあるけどたくさんありすぎて紹介しきれないので, そのうちのいくつかを紹介.

Juliaのメソッドも名前と引数のセットで認識するため, 同じ名前のメソッドでも引数に応じた複数の処理を一つの名前のメソッドに定義できます.

- methods()
- @which
- fieldnames()
- typeof()
-  @code_lowered
- ?

In [1]:
methods(copy) # methods()...ある名前で定義されているメソッドを出力

# 44 methods for generic function "copy":
copy(e::Expr) in Base at expr.jl:35
copy(s1::IntSet) in Base at intset.jl:11
copy(o::ObjectIdDict) in Base at associative.jl:475
copy(src::Base.dSFMT.DSFMT_state) in Base.dSFMT at dSFMT.jl:32
copy(src::MersenneTwister) in Base.Random at random.jl:112
copy(vset::Base.Pkg.Types.VersionSet) in Base.Pkg.Types at pkg/types.jl:66
copy(a::Base.Pkg.Types.Available) in Base.Pkg.Types at pkg/types.jl:148
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:101
copy(a::Base.Pkg.Resolve.VersionWeights.VWPreBuild) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:159
copy(a::Base.Pkg.Resolve.VersionWeights.VersionWeight) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:219
copy(a::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue) in Base.Pkg.Resolve.MaxSum.FieldValues at pkg/resolve/fieldvalue.jl:68
copy(r::Range) in Base at range.jl:430
copy(x::Number) in Base at number.jl:48
copy(a::T) where T<:Array in Base at array.jl:139
copy(M::SymTridiagonal) in Base.LinAlg at linalg/tridiag.jl:105
copy(M::Tridiagonal) in Base.LinAlg at linalg/tridiag.jl:517
copy(A::LowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitLowerTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::UpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Base.LinAlg.UnitUpperTriangular) in Base.LinAlg at linalg/triangular.jl:38
copy(A::Symmetric{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:160
copy(A::Hermitian{T,S}) where {T, S} in Base.LinAlg at linalg/symmetric.jl:161
copy(M::Bidiagonal) in Base.LinAlg at linalg/bidiag.jl:266
copy(ra::Base.ReshapedArray{#s268,2,#s267,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where #s267<:SparseMatrixCSC where #s268) in Base.SparseArrays at sparse/sparsematrix.jl:238
copy(S::SparseMatrixCSC) in Base.SparseArrays at sparse/sparsematrix.jl:253
copy(A::Base.SparseArrays.CHOLMOD.Sparse{Tv}, stype::Integer, mode::Integer) where Tv<:Float64 in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:618
copy(A::Base.SparseArrays.CHOLMOD.Sparse) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1209
copy(x::AbstractSparseArray{Tv,Ti,1} where Ti where Tv) in Base.SparseArrays at sparse/sparsevector.jl:825
copy(A::Base.SparseArrays.CHOLMOD.Dense) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1208
copy(a::AbstractArray) in Base at abstractarray.jl:697
copy(d::Dict) in Base at dict.jl:134
copy(d::WeakKeyDict) in Base at weakkeydict.jl:49
copy(a::Associative) in Base at associative.jl:113
copy(s::Set) in Base at set.jl:41
copy(b::Base.AbstractIOBuffer) in Base at iobuffer.jl:81
copy(A::Base.LinAlg.LQ) in Base.LinAlg at linalg/lq.jl:48
copy(C::Base.LinAlg.Cholesky) in Base.LinAlg at linalg/cholesky.jl:416
copy(C::Base.LinAlg.CholeskyPivoted) in Base.LinAlg at linalg/cholesky.jl:417
copy(J::UniformScaling) in Base.LinAlg at linalg/uniformscaling.jl:41
copy(F::Base.LinAlg.Schur) in Base.LinAlg at linalg/schur.jl:288
copy(F::Base.LinAlg.GeneralizedSchur) in Base.LinAlg at linalg/schur.jl:289
copy(a::Base.Pkg.Resolve.VersionWeights.HierarchicalValue{T}) where T in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:71
copy(A::Base.SparseArrays.CHOLMOD.Factor) in Base.SparseArrays.CHOLMOD at sparse/cholmod.jl:1210
copy(md::MbedTLS.MD) in MbedTLS at /Users/U05284/.julia/v0.6/MbedTLS/src/md.jl:93

In [2]:
@which(copy([1, 2, 3])) # @which...どの引数の処理のメソッドが呼ばれているかを出力

copy(a::T) where T<:Array in Base at array.jl:139

In [3]:
fieldnames(Hermitian) # filednames()...インスタンスや構造体の中身のタイプを出力

2-element Array{Symbol,1}:
 :data
 :uplo

In [4]:
typeof([1;2;3]) # typeof()... 型を出力, c.f. ;は改行, つまりこれは列ベクトル

Array{Int64,1}

In [5]:
@code_lowered sin(sqrt(3)) # @code_lowered...どんな処理が発生してるかを確認できる. sqrt()は√3でもok.

CodeInfo(:(begin 
        nothing
        nothing
        SSAValue(0) = (Base.cconvert)(Base.Math.Float64, x)
        SSAValue(1) = $(Expr(:foreigncall, :((Core.tuple)("sin", Base.Math.libm)), Float64, svec(Float64), :((Base.unsafe_convert)(Base.Math.Float64, SSAValue(0))), SSAValue(0)))
        return (Base.Math.nan_dom_err)(SSAValue(1), x)
    end))

またIntractiveShellにてjuliaを使っている場合だけですが.コンソール時に"?"を打ち込むとhelpモードに入ります.

In [6]:
# ?copy...copyのヘルプが出ます

-----

## 2.Array
基本的な構文はmatlabと同じ.

### 宣言方法と代入方法

In [7]:
a = Vector{Float64}(5) #5つのfloat64値からなる一次元配列の生成
a = [1 2 3 4 5]

cv = [1;2;3;4;5] # 列ベクトル
rv = [1 2 3 4 5] # 行ベクトル

println(cv)
println(rv)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
a[3] = 100 # 配列aの"3つめ"の要素を100に変更. 線形indexを使用しています.
a

1×5 Array{Int64,2}:
 1  2  100  4  5

In [9]:
b = Matrix{Float64}(4,2) # size(4, 2)からなるFloat64型行列を生成

c = Array{Float64}(4,5,6,7) # (4,5,6,7)からなるFloat64配列

mat =  [11 12 13 14
        21 22 23 24
        31 32 33 34] # 直接inlineでMatrixの宣言も可能

3×4 Array{Int64,2}:
 11  12  13  14
 21  22  23  24
 31  32  33  34

In [10]:
mat[1,2] = 4 # 変更方法は同じ.
mat

3×4 Array{Int64,2}:
 11   4  13  14
 21  22  23  24
 31  32  33  34

#### memo1
> memo1: REPL環境を使ってる時, 評価された時に値を返される物の後ろに";"を入れると出力を無視できます.  
> memo2: arrayの値はメモリの場所へのポインタです.

In [11]:
#memo1
mat;

In [12]:
#memo2
a = [1;2;3]
b = a
b[1] = 10
println(a, b)

[10, 2, 3][10, 2, 3]


In [13]:
#memo2: aも一緒に変更されたくない場合は"copy"を使います.
a = [1;2;3]
b = copy(a)
b[1] = 10
println(a, b)

[1, 2, 3][10, 2, 3]


#### memo2
他にもコンストラクタを使わずにも宣言することが可能です. その場合以下のメソッドが有用.  
いずれも, 引数のArrayのsize/shapeを引き継いだ新しいArrayを返します.

- similar()
- zeros()
- ones()

In [14]:
simA = similar(a) # aと同じ構造の未初期化のaryを返す.
zerosA = zeros(a) # aと同じ構造の全て0のaryを返す.
onesA = ones(a) # aと同じ構造の全て1のaryを返す.

println(simA, zerosA, onesA)

[4469783144, 4469783576, 4469791928][0, 0, 0][1, 1, 1]


#### memo3
1) 配列は[a:b]によって切り出すことが可能.
- [a:b]...配列のa番目からb番目までを切り出す

2) また, aryにはどんな種類のtypeも内包できるため配列の中に配列を含めることももちろん可能です.


In [15]:
#1)
a = [1 2 3 4 5 6 7 8 9 10]
a[1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [16]:
# 2)
a = Vector{Vector{Float64}}(3)
a[1] = [1;2;3]
a[2] = [1;2]
a[3] = [3;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [1.0, 2.0]     
 [3.0, 4.0, 5.0]

また, 入れ子構造になったarrayのcopyにはdeepcopy()を使います.

In [17]:
b = deepcopy(a)
b[1] = [1;3;2]
println(a)
println(b)

Array{Float64,1}[[1.0, 2.0, 3.0], [1.0, 2.0], [3.0, 4.0, 5.0]]
Array{Float64,1}[[1.0, 3.0, 2.0], [1.0, 2.0], [3.0, 4.0, 5.0]]


#### memo4
高い実行速度を達成するためにはコード量を減らすことが重要です. 
そのため, Juliaには引数に破壊的代入をもたらすmutationメソッドがあり, そのようなメソッドの末尾には!が付いています.

In [18]:
# mutation method ex.
a = [1;6;9]
scale!(a, 2) # scale!(ary, scalar)...aryをscalar倍

3-element Array{Int64,1}:
  2
 12
 18

----

## 3.制御フロー

Juliaの制御フローは他のスクリプト言語と大して変化はなし.
いつも通りのfor loop, while, ifがあるくらい.

他のものはdocumentを参照.

In [19]:
# for loop
for i=1:5 #1:5でrange, =をinに変えても実行可能.
  println(i)
end

1
2
3
4
5


In [20]:
t = 0
while t < 5
  println(t)
  t+=1
end

0
1
2
3
4


In [21]:
symbol = :asdf

if symbol == :asdf
  println("you said asdf")
else
  println("no idea")
end

you said asdf
search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: for foreach UniformScaling DateFormat @dateformat_str foldr floor

search: end endof endswith ENDIAN_BOM send append! QuoteNode RangeIndex getindex



#### memo
Juliaのforloopで面白いのは, なんと多重for loopを一列で書ける

In [22]:
for i=1:5, j=2:4
  println(i*j)
end

2
3
4
4
6
8
6
9
12
8
12
16
10
15
20


### 練習問題
http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems
上5問.

制御flow理解できてれば実装できるはず.

#### Q1. (N,N)型で, 体格が-2, 体格の左右隣が1, それ以外が0の行列を作れ. ストラング行列っていうとか

In [62]:
N = 5
#mat = Matrix{Float64}(N, N)
mat = zeros(N, N)
for i=1:N, j=1:N
  if i==j
    mat[i,j] = -2
  elseif i==j+1||i==j-1
    mat[i,j] = 1
  end
end

mat

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

##### Q1. 綺麗なコードver. こっちの方が"juliaらしい"

In [71]:
N=5
A = zeros(N,N)
for i=1:N, j=1:N
  abs(i-j)==1 && (A[i,j]=1)
  i==j && (A[i,j]=-2)
end
A

5×5 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   1.0  -2.0

#### Q2. 階上, my_factorial(n)で, n!を出力.

In [73]:
function my_factorial(n)
  ans = 1
  for i=1:n
    ans*=i
  end
  ans  
end
my_factorial(15)
#c.f. ただしこれでは大きい値を扱う形になった時にOverFlowが発生する.(ex. 30を入れるとnegativeになる)

1307674368000

##### こういう時は入力と出力の型を同じにすればよい. one(x)を使用する

In [75]:
function my_factorial(n)
  k = one(n) # one(x)...xと同じ型で値1の数値を返す.
  for i=1:n
    k *= i
  end
  k
end
my_factorial(big(30))

265252859812191058636308480000000

#### Q3.二項問題
nを試行回数, pを成功する確率とした時, n回の内成功した回数XをX=Bin(n,p)と表すとする.  
例えば, Bin(10, 0.5)の時, Xは10回コインを投げた時に表が出てくる回数に等しい.  
  
Xを返すbinomial_rv(n,p)をrand()を用いて実装せよ

In [76]:
function binomial_rv(n,p)
  k=0
  for i=1:n
    p<=rand() && (k+=1)
  end
  k
end

#check
[binomial_rv(10, 0.5) for i=1:5]

5-element Array{Int64,1}:
 5
 2
 3
 4
 5

#### Q4. モンテカルロによる円周率の計算
πを乱数を用いて近似せよ.

**Hint: モンテカルロ法**
[-1, 1]×[-1, 1]の四角形に内包される円があった時, *円の面積はπ*($πr^2$より), *四角形の面積は4*.  
そのため, 乱数を用いて[-1,1]×[-1,1]の部分に一様な乱数で点を打った時, *円周の中に打たれる確率はπ/4*($x^2+y^2$≦1より).  
これを用いてπの大体の値を求めよ.

In [140]:
function montecarlo(n)
  c = 0
  for _=1:n
    x, y = 2rand(2)-1
    sqrt(x^2+y^2)<=1 && (c+=1)
  end
  return 4c/n
end

montecarlo(10000000)

3.1420824

#### Q5. 時系列生成問題
AR1時系列は, $x_{t+1} = \alpha x_i + \epsilon_{t+1}$ では定義されたとする.  
この時それぞれ, $x_0$=0, t=0...T, ソケット$\epsilon_{t}$は独立同分布である(N(0,1)はrandn()によって与えられるとする).  
  
T=200の時,

- α=0
- α=0.5
- α=0.9

の場合のそれぞれのパラメータの時間変化をPlot.jlを用いて示せ.  
また, αの値を表す線にはplot関数にlabelオプションをつけ, ラベルせよ.

In [2]:
using Plots

function _ar(T, a)
  d=[0.0]
  tmp=0.0
  for i=1:T
    e = randn()
    tmp = a*tmp + e
    push!(d, tmp)
  end
  d
end

_ar (generic function with 1 method)

In [8]:
ar_(T) = a -> _ar(T, a)
ar = ar_(200)

ar1 = ar(0)
ar2 = ar(0.5)
ar3 = ar(0.9)

gr()
plot([ar1, ar2, ar3])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 30 
 
 
 60 
 
 
 90 
 
 
 120 
 
 
 150 
 
 
 180 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
<polyline clip-path="url(#clip4802)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 39.3701,220.351 42.1339,258.362 44.8976,266.325 47.6614,239.087 50.4252,279.042 53.189,177.967 55.9528,162.852 58.7165,164.263 61.4803,226.34 64.2441,232.245 
 67.0079,221.587 69.7717,204.718 72.5354,200.589 75.2992,262.105 78.063,242.969 80.8268,208.166 83.5906,242.169 86.3543,257.908 89.1181,214.947 91.8819,210.173 
 94.6457,226.609 97.4094,278.289 100.173,233.294 102.937,164.618 105.701,156.465 108.465,239.748 111.228,164.003 113.992,224.873 116.756,216.065 119.52,219.86 
 122.283,168.928 125.047,156.371 127.811,243.914 130.575,195.571 133.339,220.56 136.102,217.603 138.866,214.93 141.63,212.767 144.394,205.881 147.157,212.283 
 149.921,214.822 152.685,208.032 155.449,175.202 158.213,274.161 160.976,233.725 163.74,200.784 166.504,203.55 169.268,237.063 172.031,158.862 174.795,229.928 
 177.559,193.412 180.323,265.564 183.087,204.093 185.85,234.166 188.614,202.429 191.378,222.667 194.142,242.365 196.906,190.478 199.669,245.603 202.433,209.063 
 205.197,268.256 207.961,255.769 210.724,261.162 213.488,210.402 216.252,244.078 219.016,240.352 221.78,238.685 224.543,244.307 227.307,266.824 230.071,222.802 
 232.835,235.296 235.598,207.858 238.362,209.953 241.126,258.873 243.89,281.566 246.654,184.177 249.417,244.2 252.181,222.153 254.945,210.461 257.709,220.422 
 260.472,211.594 263.236,233.029 266,230.427 268.764,204.335 271.528,232.942 274.291,260.088 277.055,222.841 279.819,218.153 282.583,185.292 285.346,221.684 
 288.11,209.673 290.874,265.375 293.638,224.618 296.402,252.991 299.165,230.702 301.929,239.168 304.693,217.076 307.457,247.951 310.22,192.3 312.984,175.672 
 315.748,248.004 318.512,254.273 321.276,213.743 324.039,191.214 326.803,287.709 329.567,202.448 332.331,138.542 335.094,218.2 337.858,229.454 340.622,207.605 
 343.386,213.468 346.15,264.162 348.913,204.111 351.677,239.554 354.441,243.863 357.205,237.123 359.969,236.368 362.732,227.447 365.496,259.143 368.26,235.563 
 371.024,247.225 373.787,199.157 376.551,248.173 379.315,213.575 382.079,249.231 384.843,275.258 387.606,197.865 390.37,241.109 393.134,217.078 395.898,240.613 
 398.661,224.073 401.425,239.477 404.189,262.136 406.953,282.606 409.717,201.749 412.48,239.916 415.244,181.601 418.008,191.022 420.772,181.357 423.535,262.534 
 426.299,265.743 429.063,222.595 431.827,216.727 434.591,191.145 437.354,240.507 440.118,233.347 442.882,251.025 445.646,223.377 448.409,219.029 451.173,232.603 
 453.937,242.243 456.701,239.277 459.465,153.552 462.228,228.319 464.992,144.209 467.756,206.091 470.52,205.708 473.283,201.368 476.047,243.935 478.811,183.773 
 481.575,234.756 484.339,227.626 487.102,253.266 489.866,208.83 492.63,212.56 495.394,210.667 498.157,223.43 500.921,188.255 503.685,256.687 506.449,247.311 
 509.213,254.602 511.976,199.832 514.74,169.743 517.504,218.357 520.268,197.865 523.031,208.202 525.795,201.117 528.559,146.872 531.323,216.563 534.087,178.725 
 536.85,224.883 539.614,259.715 542.378,218.291 545.142,250.553 547.906,275.368 550.669,215.848 553.433,260.695 556.197,240.149 558.961,192.523 561.724,256.917 
 564.488,264.634 567.252,236.411 570.016,203.093 572.78,234.514 575.543,221.173 578.307,230.846 581.071,231.585 583.835,251.08 586.598,199.984 589.362,187.809 
 592.126,255.173 
 "/>
<polyline clip-path="url(#clip4802)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 39.3701,220.351 42.1339,251.074 44.8976,241.208 47.6614,246.76 50.4252,290.908 53.189,239.019 55.9528,200.942 58.7165,239.617 61.4803,189.241 64.2441,151.923 
 67.0079,172.608 69.7717,205.193 72.5354,183.422 75.2992,202.68 78.063,240.464 80.8268,199.555 83.5906,237.714 86.3543,208.291 89.1181,146.662 91.8819,16